<?php
namespace App\Http\Controllers\Auth;
use App\Http\Controllers\Controller;use App\Models\ConsentRecord;use App\Models\Profile;use App\Models\User;use App\Support\Audit;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Validation\Rules\Password;
class MemberAuthController extends Controller{
 public function loginForm(){return view('auth.login');}
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|string']);if(!Auth::attempt(['email'=>strtolower($d['email']),'password'=>$d['password'],'status'=>'active'],$r->boolean('remember')))return back()->withErrors(['email'=>'Invalid credentials or account unavailable.'])->onlyInput('email');$user=$r->user();if($user->two_factor_confirmed_at){$r->session()->put(['auth.2fa_user'=>$user->id,'auth.2fa_remember'=>$r->boolean('remember'),'auth.2fa_intended'=>$r->session()->pull('url.intended','/dashboard')]);Auth::logout();return redirect()->route('two-factor.challenge');}$r->session()->regenerate();$user->forceFill(['last_login_at'=>now()])->save();Audit::write('auth.login',$user,request:$r);return redirect()->intended(route('dashboard'));}
 public function registerForm(){return view('auth.register');}
 public function register(Request $r){$d=$r->validate(['name'=>'required|string|max:120','display_name'=>'required|string|max:80','email'=>'required|email|max:190|unique:users,email','date_of_birth'=>['required','date','before_or_equal:'.now()->subYears(18)->toDateString()],'password'=>['required','confirmed',Password::min(10)->letters()->numbers()],'adult'=>'accepted','terms'=>'accepted','privacy'=>'accepted']);$now=now();$u=User::create(['name'=>$d['name'],'display_name'=>$d['display_name'],'email'=>strtolower($d['email']),'date_of_birth'=>$d['date_of_birth'],'password'=>$d['password'],'status'=>'active','adult_confirmed_at'=>$now,'terms_accepted_at'=>$now,'privacy_accepted_at'=>$now,'privacy_version'=>config('platform.privacy_version','1.0')]);Profile::create(['user_id'=>$u->id,'profile_type'=>'individual','visibility'=>['bio'=>'members','photos'=>'members'],'discoverable'=>true]);foreach(['adult_terms','privacy'] as $type)ConsentRecord::create(['user_id'=>$u->id,'consent_type'=>$type,'document_version'=>$type==='privacy'?config('platform.privacy_version','1.0'):config('platform.terms_version','1.0'),'granted'=>true,'ip_hash'=>hash('sha256',(string)$r->ip().config('app.key')),'recorded_at'=>$now]);Auth::login($u);$r->session()->regenerate();try{$u->sendEmailVerificationNotification();}catch(\Throwable){}Audit::write('auth.register',$u,request:$r);return redirect()->route('dashboard')->with('status','Account created. Check your email for a verification link if email delivery is configured.');}
 public function logout(Request $r){Audit::write('auth.logout',$r->user(),request:$r);Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect()->route('site.home');}
}