<?php
namespace App\Http\Controllers\Auth;
use App\Http\Controllers\Controller;use App\Models\SecurityEvent;use App\Models\User;use App\Services\TotpService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Facades\Crypt;
class TwoFactorChallengeController extends Controller{
 public function create(Request $r){abort_unless($r->session()->has('auth.2fa_user'),404);return view('auth.two-factor-challenge');}
 public function store(Request $r,TotpService $totp){$d=$r->validate(['code'=>'required|string|max:30']);$id=$r->session()->get('auth.2fa_user');$user=User::where('status','active')->findOrFail($id);$valid=false;$recoveryUsed=false;try{$secret=Crypt::decryptString((string)$user->two_factor_secret);$valid=$totp->verify($secret,$d['code']);}catch(\Throwable){}
  if(!$valid){try{$codes=json_decode(Crypt::decryptString((string)$user->two_factor_recovery_codes),true)?:[];$needle=strtolower(trim($d['code']));$index=array_search($needle,$codes,true);if($index!==false){unset($codes[$index]);$user->forceFill(['two_factor_recovery_codes'=>Crypt::encryptString(json_encode(array_values($codes)))])->save();$valid=true;$recoveryUsed=true;}}catch(\Throwable){}}
  if(!$valid){SecurityEvent::create(['user_id'=>$user->id,'event'=>'2fa.failed','ip_hash'=>hash('sha256',(string)$r->ip().config('app.key')),'user_agent_hash'=>hash('sha256',(string)$r->userAgent()),'occurred_at'=>now()]);return back()->withErrors(['code'=>'The authentication code was not accepted.']);}
  $remember=(bool)$r->session()->pull('auth.2fa_remember',false);$intended=(string)$r->session()->pull('auth.2fa_intended','/dashboard');$r->session()->forget('auth.2fa_user');Auth::login($user,$remember);$r->session()->regenerate();$user->forceFill(['last_login_at'=>now()])->save();SecurityEvent::create(['user_id'=>$user->id,'event'=>$recoveryUsed?'2fa.recovery_used':'2fa.success','ip_hash'=>hash('sha256',(string)$r->ip().config('app.key')),'user_agent_hash'=>hash('sha256',(string)$r->userAgent()),'occurred_at'=>now()]);return redirect($intended);
 }
}