@extends('layouts.app')
@section('title', $event->exists ? 'Edit Event' : 'Create Event')
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">CLUB OS · EVENT STUDIO</span><h1>{{ $event->exists ? 'Shape every detail of '.$event->title : 'Create an experience worth saving.' }}</h1><p>Build admission, privacy, schedule, hosts, visual story, FAQ, updates and guest flow from one workspace.</p>@if($event->exists)<div class="pg-actions"><a class="button button-ghost" href="{{ route('events.show',$event) }}" target="_blank" rel="noopener">Preview event</a><a class="button button-ghost" href="{{ route('tenant.events.attendees',$event) }}">Attendees</a><a class="button button-ghost" href="{{ route('tenant.events.waitlist.index',$event) }}">Waitlist</a></div>@endif</div></section>
<section class="pg-page"><div class="pg-shell">
<form method="post" class="pg-card form-stack" action="{{ $event->exists ? route('tenant.events.update', $event) : route('tenant.events.store') }}">@csrf @if($event->exists) @method('put') @endif
<div class="panel-head"><div><span class="pg-eyebrow">CORE DETAILS</span><h2>What guests need to know</h2><p class="muted">Keep public discovery useful while reserving exact private details for the access level you choose.</p></div><span class="pg-pill">{{ ucfirst($event->status ?: 'draft') }}</span></div>
<div class="form-grid">
<label>Title<input name="title" value="{{ old('title',$event->title) }}" required maxlength="180"></label><label>Slug<input name="slug" value="{{ old('slug',$event->slug) }}" maxlength="180"></label>
<label>Starts<input type="datetime-local" name="starts_at" value="{{ old('starts_at',$event->starts_at?->format('Y-m-d\TH:i')) }}" required></label><label>Ends<input type="datetime-local" name="ends_at" value="{{ old('ends_at',$event->ends_at?->format('Y-m-d\TH:i')) }}"></label>
<label>Timezone<input name="timezone" value="{{ old('timezone',$event->timezone ?: config('app.timezone')) }}" required></label><label>Capacity<input type="number" name="capacity" min="1" max="100000" value="{{ old('capacity',$event->capacity) }}" placeholder="Unlimited"></label>
<label>Visibility<select name="visibility">@foreach(['public'=>'Public','members'=>'Members','unlisted'=>'Unlisted','invite_only'=>'Invite only','private'=>'Private'] as $value=>$label)<option value="{{$value}}" @selected(old('visibility',$event->visibility ?: 'public')===$value)>{{$label}}</option>@endforeach</select></label>
<label>RSVP method<select name="rsvp_mode">@foreach(['instant'=>'Instant','approval'=>'Approval','application'=>'Application','invite_only'=>'Invite only'] as $value=>$label)<option value="{{$value}}" @selected(old('rsvp_mode',$event->rsvp_mode ?: 'instant')===$value)>{{$label}}</option>@endforeach</select></label>
<label>Status<select name="status">@foreach(['draft','published','cancelled'] as $value)<option value="{{$value}}" @selected(old('status',$event->status ?: 'draft')===$value)>{{ucfirst($value)}}</option>@endforeach</select></label><label>Category<input name="category" value="{{ old('category',$event->category) }}" placeholder="Social, theme night, meet & greet"></label>
<label>City<input name="city" value="{{ old('city',$event->city) }}"></label><label>State / region<input name="region" value="{{ old('region',$event->region) }}"></label>
<label class="span2">Public location label<input name="public_location_label" value="{{ old('public_location_label',$event->public_location_label) }}" placeholder="Dallas area · Uptown"></label>
<label class="span2">Exact address<input name="exact_address" value="{{ old('exact_address',$event->exact_address) }}" autocomplete="street-address"></label>
<label>Address visibility<select name="exact_address_visibility">@foreach(['approved_attendees'=>'Approved attendees','organizer_only'=>'Organizer only','public'=>'Public'] as $value=>$label)<option value="{{$value}}" @selected(old('exact_address_visibility',$event->exact_address_visibility ?: 'approved_attendees')===$value)>{{$label}}</option>@endforeach</select></label><label>Dress code<input name="dress_code" value="{{ old('dress_code',$event->dress_code) }}"></label>
<label>Registration opens<input type="datetime-local" name="registration_opens_at" value="{{ old('registration_opens_at',$event->registration_opens_at?->format('Y-m-d\TH:i')) }}"></label><label>Registration closes<input type="datetime-local" name="registration_closes_at" value="{{ old('registration_closes_at',$event->registration_closes_at?->format('Y-m-d\TH:i')) }}"></label>
<label>Repeat<select name="recurrence_rule"><option value="">Do not repeat</option><option value="weekly" @selected(old('recurrence_rule',$event->recurrence_rule)==='weekly')>Weekly</option><option value="monthly" @selected(old('recurrence_rule',$event->recurrence_rule)==='monthly')>Monthly</option></select></label><label>Repeat until<input type="date" name="recurrence_until" value="{{ old('recurrence_until',$event->recurrence_until?->format('Y-m-d')) }}"></label>
<label class="span2">Summary<textarea name="summary" rows="3" maxlength="1000">{{ old('summary',$event->summary) }}</textarea></label><label class="span2">Description<textarea rows="7" name="description" maxlength="30000">{{ old('description',$event->description) }}</textarea></label><label class="span2">Rules & consent expectations<textarea rows="5" name="rules" maxlength="10000" placeholder="Consent, phones/photos, privacy, intoxication, conduct and event-specific expectations">{{ old('rules',$event->rules) }}</textarea></label>
</div>
@include('tenant.manage.events._experience')
<div class="pg-grid pg-grid-2"><label class="pg-card row-actions"><input type="checkbox" name="waitlist_enabled" value="1" @checked(old('waitlist_enabled',$event->exists ? $event->waitlist_enabled : true))><span><strong>Automatic waitlist</strong><small>Offer a queue when capacity is reached.</small></span></label><label class="pg-card row-actions"><input type="checkbox" name="requires_verified_profile" value="1" @checked(old('requires_verified_profile',$event->requires_verified_profile))><span><strong>Verified profile required</strong><small>Require the established adult/member verification gate.</small></span></label></div>
@if($errors->any())<div class="error" role="alert">{{$errors->first()}}</div>@endif<div class="pg-actions"><button class="button button-primary">{{ $event->exists ? 'Save event changes' : 'Create event' }}</button><a class="button button-ghost" href="{{route('tenant.events.index')}}">Cancel</a></div>
</form>

@if($event->exists)
<section class="pg-section"><div class="pg-grid pg-grid-2">
<article class="pg-card"><span class="pg-eyebrow">ADMISSION</span><h2>Tickets & eligibility</h2><p class="muted">Profile, membership and event-approval rules are rechecked at checkout.</p>@forelse($event->ticketTypes as $ticketType)<div class="list-row"><div><strong>{{$ticketType->name}}</strong><small>{{$ticketType->price_cents?'$'.number_format($ticketType->price_cents/100,2):'Free'}} · {{$ticketType->quantity??'Unlimited'}} · {{$ticketType->eligibilityLabel()}} @if($ticketType->membership_required) · Members @endif @if($ticketType->approval_required) · Approved RSVP @endif</small></div></div>@empty<div class="pg-empty">No ticket types yet.</div>@endforelse
<form class="form-stack" method="post" action="{{route('tenant.ticket-types.store',$event)}}">@csrf<div class="form-grid"><label>Ticket name<input name="name" required placeholder="Couple admission"></label><label>Eligible profile<select name="profile_eligibility"><option value="any">Any eligible profile</option><option value="couple">Couple only</option><option value="individual">Individual only</option></select></label><label>Price<input name="price" type="number" step="0.01" min="0" value="0"></label><label>Quantity<input name="quantity" type="number" min="1" placeholder="Unlimited"></label><label>Max per order<input name="max_per_order" type="number" min="1" value="10"></label><label class="span2">Description<textarea name="description" rows="3"></textarea></label></div><label class="row-actions"><input type="checkbox" name="membership_required" value="1"> Active membership required</label><label class="row-actions"><input type="checkbox" name="approval_required" value="1"> Approved event attendance required</label><button class="button button-ghost">Add ticket type</button></form></article>
<article class="pg-card"><span class="pg-eyebrow">SCREENING</span><h2>RSVP questions</h2>@forelse($questions as $question)<div class="row-between"><span>{{$question->label}} · {{$question->type}}</span><form method="post" action="{{route('tenant.events.questions.destroy',[$event,$question->id])}}">@csrf @method('delete')<button class="button button-ghost">Delete</button></form></div>@empty<div class="pg-empty">No custom questions.</div>@endforelse<form class="form-stack" method="post" action="{{route('tenant.events.questions.store',$event)}}">@csrf<label>Question<input name="label" required></label><label>Answer type<select name="type"><option value="text">Text</option><option value="textarea">Long text</option><option value="select">Select</option><option value="checkbox">Confirmation</option></select></label><label class="row-actions"><input type="checkbox" name="required" value="1"> Required</label><button class="button button-ghost">Add question</button></form></article>
</div></section>
<section class="pg-section pg-card"><div class="panel-head"><div><span class="pg-eyebrow">PRIVATE INVITATIONS</span><h2>Controlled access links</h2><p class="muted">Only a one-way token digest is stored. The raw invitation URL is shown once.</p></div></div>@if(session('event_invitation_url'))<div class="success" role="status"><strong>Copy this secure link now.</strong><code style="display:block;overflow-wrap:anywhere;margin-top:8px">{{session('event_invitation_url')}}</code></div>@endif<form class="form-inline" method="post" action="{{route('tenant.events.invitations.store',$event)}}">@csrf<label>Recipient email<input type="email" name="email" placeholder="Optional"></label><label>Guest allowance<input type="number" name="max_guests" min="1" max="10" value="1" required></label><label>Expires<input type="datetime-local" name="expires_at"></label><button class="button button-primary">Create invitation</button></form><div class="pg-grid">@forelse($invitations??[] as $invitation)<div class="row-between"><div><strong>{{$invitation->email?:'Open invitation link'}}</strong><small>{{ucfirst($invitation->status)}} · up to {{$invitation->max_guests}} guest(s) @if($invitation->expires_at) · expires {{$invitation->expires_at->format('M j, Y g:i A')}} @endif</small></div>@if($invitation->status==='pending')<form method="post" action="{{route('tenant.events.invitations.revoke',[$event,$invitation])}}">@csrf @method('delete')<button class="button button-ghost">Revoke</button></form>@endif</div>@empty<div class="pg-empty">No invitations yet.</div>@endforelse</div></section>
<section class="pg-section"><div class="pg-actions"><form method="post" action="{{route('tenant.events.duplicate',$event)}}">@csrf<button class="button button-ghost">Duplicate as draft</button></form><form method="post" action="{{route('tenant.events.destroy',$event)}}" onsubmit="return confirm('Delete this event? Events with orders cannot be deleted.')">@csrf @method('delete')<button class="button button-ghost danger">Delete event</button></form></div></section>
@endif
</div></section>
@endsection
