@extends('layouts.admin')
@section('title','Website Content')
@section('content')
<div class="pg-admin-page-head"><div><span class="pg-admin-kicker">Platform</span><h1>Website Content & Theme</h1><p>Edit the central Private Gather marketplace and choose a complete presentation system. Tenant themes remain separate so every club can keep its own identity.</p></div><a class="button button-ghost" href="{{route('site.home')}}" target="_blank" rel="noopener">Preview live marketplace</a></div>
@if(session('status'))<div class="alert alert-success" role="status">{{session('status')}}</div>@endif
<form method="post" enctype="multipart/form-data" action="{{route('admin.content.update')}}" class="pg-admin-card form-card wide">@csrf @method('patch')
<div class="pg-admin-card" style="margin-bottom:18px"><div class="row-between"><div><span class="pg-admin-kicker">Official identity</span><h2>Private Gather crest</h2><p>The central marketplace always uses the official crest. Themes may resize or reposition it but never silently replace the product identity.</p></div><img src="{{\App\Support\MountUrl::to('/assets/branding/private-gather-logo.png')}}" alt="Official Private Gather logo" style="width:150px;max-height:110px;object-fit:contain"></div></div>

<div class="pg-admin-card" style="margin-bottom:18px"><span class="pg-admin-kicker">Main-site theme</span><h2>Choose the whole visual system</h2><p>Each preview represents navigation density, hero balance, typography rhythm and card geometry—not merely an accent color.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px">@foreach($platformThemes as $key=>$theme)@php($selected=old('theme_preset',$content['theme_preset'])===$key)<label class="pg-theme-choice" style="display:block;padding:0;overflow:hidden;cursor:pointer;border:{{$selected?'2px solid #d9bc78':'1px solid rgba(255,255,255,.14)'}};border-radius:16px;background:#111"><div aria-hidden="true" style="min-height:155px;padding:16px;background:{{match($theme['layout']){'editorial'=>'linear-gradient(135deg,#f0ece5 0 50%,#171719 50%)','neon'=>'radial-gradient(circle at 70% 25%,#9d2cff 0,#24132f 30%,#09080d 70%)','society'=>'linear-gradient(145deg,#080808,#231b0d 70%,#4c3a17)','modern'=>'linear-gradient(135deg,#15161a,#2a2930 55%,#18121f)',default=>'radial-gradient(circle at 70% 20%,#47243f,#151018 42%,#09090c 78%)'}}"><div style="height:10px;width:45%;border-radius:10px;background:rgba(217,188,120,.85);margin-bottom:34px"></div><div style="height:22px;width:72%;border-radius:6px;background:{{$theme['layout']==='editorial'?'rgba(10,10,10,.82)':'rgba(255,255,255,.88)'}};margin-bottom:10px"></div><div style="height:8px;width:88%;border-radius:6px;background:{{$theme['layout']==='editorial'?'rgba(10,10,10,.34)':'rgba(255,255,255,.28)'}};margin-bottom:18px"></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:7px"><span style="height:34px;border-radius:7px;background:rgba(217,188,120,.2);border:1px solid rgba(217,188,120,.3)"></span><span style="height:34px;border-radius:7px;background:rgba(255,255,255,.08)"></span><span style="height:34px;border-radius:7px;background:rgba(255,255,255,.08)"></span></div></div><div style="padding:14px"><span class="row-actions"><input type="radio" name="theme_preset" value="{{$key}}" @checked($selected)><strong>{{$theme['label']}}</strong></span><small style="display:block;margin-top:6px">{{$theme['description']}}</small><span class="pill" style="display:inline-flex;margin-top:10px">{{ucfirst($theme['layout'])}} layout</span></div></label>@endforeach</div></div>

<div class="pg-admin-card" style="margin-bottom:18px"><div class="row-between"><div><span class="pg-admin-kicker">Showcase population</span><h2>Populate a credible demo marketplace</h2><p>Add or refresh ten fictional clubs and twenty future events across different cities and tenant themes. The seeder is deterministic/idempotent and clearly marks showcase content in tenant settings.</p></div><button type="submit" name="action" value="seed_showcase" formnovalidate>Refresh Showcase Marketplace</button></div></div>

<div class="form-grid"><label>Brand name<input name="brand_name" value="{{old('brand_name',$content['brand_name'])}}" required></label><label>Header join label<input name="header_cta_label" value="{{old('header_cta_label',$content['header_cta_label'])}}"></label><label class="span2">Header join URL<input name="header_cta_url" value="{{old('header_cta_url',$content['header_cta_url'])}}"></label>
<label>Hero eyebrow<input name="hero_eyebrow" value="{{old('hero_eyebrow',$content['hero_eyebrow'])}}"></label><label>Hero heading<input name="hero_heading" value="{{old('hero_heading',$content['hero_heading'])}}"></label><label class="span2">Hero body<textarea name="hero_body" rows="4">{{old('hero_body',$content['hero_body'])}}</textarea></label><label>Hero image URL (optional)<input name="hero_image_url" value="{{old('hero_image_url',$content['hero_image_url'])}}"></label><label>Or upload hero image<input type="file" name="hero_image" accept="image/jpeg,image/png,image/webp"></label><label>Primary button label<input name="hero_primary_label" value="{{old('hero_primary_label',$content['hero_primary_label'])}}"></label><label>Primary button URL<input name="hero_primary_url" value="{{old('hero_primary_url',$content['hero_primary_url'])}}"></label><label>Secondary button label<input name="hero_secondary_label" value="{{old('hero_secondary_label',$content['hero_secondary_label'])}}"></label><label>Secondary button URL<input name="hero_secondary_url" value="{{old('hero_secondary_url',$content['hero_secondary_url'])}}"></label>
<label>Featured eyebrow<input name="featured_eyebrow" value="{{old('featured_eyebrow',$content['featured_eyebrow'])}}"></label><label>Featured heading<input name="featured_heading" value="{{old('featured_heading',$content['featured_heading'])}}"></label><label>Organizations eyebrow<input name="organizations_eyebrow" value="{{old('organizations_eyebrow',$content['organizations_eyebrow'])}}"></label><label>Organizations heading<input name="organizations_heading" value="{{old('organizations_heading',$content['organizations_heading'])}}"></label><label>Domain eyebrow<input name="domain_eyebrow" value="{{old('domain_eyebrow',$content['domain_eyebrow'])}}"></label><label>Domain heading<input name="domain_heading" value="{{old('domain_heading',$content['domain_heading'])}}"></label><label class="span2">Domain section text<textarea name="domain_body" rows="3">{{old('domain_body',$content['domain_body'])}}</textarea></label><label class="span2">Footer text<textarea name="footer_text" rows="3">{{old('footer_text',$content['footer_text'])}}</textarea></label><label>About heading<input name="about_heading" value="{{old('about_heading',$content['about_heading'])}}"></label><label>About image URL<input name="about_image_url" value="{{old('about_image_url',$content['about_image_url'])}}"></label><label>Or upload about image<input type="file" name="about_image" accept="image/jpeg,image/png,image/webp"></label><label class="span2">About text<textarea name="about_body" rows="6">{{old('about_body',$content['about_body'])}}</textarea></label></div>
<div class="row-actions"><label class="checkbox-line"><input type="checkbox" name="show_featured_events" value="1" @checked(($content['show_featured_events']??'1')==='1')> Show featured events</label><label class="checkbox-line"><input type="checkbox" name="show_organizations" value="1" @checked(($content['show_organizations']??'1')==='1')> Show organizations</label><label class="checkbox-line"><input type="checkbox" name="show_domain_section" value="1" @checked(($content['show_domain_section']??'1')==='1')> Show custom-domain section</label></div>
@if($errors->any())<div class="alert alert-danger" role="alert">{{$errors->first()}}</div>@endif<button type="submit">Save Website & Theme</button></form>
@endsection
