@extends('layouts.admin')
@section('title','Website Content')
@section('content')
<div class="pg-admin-page-head"><div><span class="pg-admin-kicker">Platform</span><h1>Website Content</h1><p>Edit Private Gather marketplace branding, text, images and optional homepage sections without modifying source code.</p></div></div>
<form method="post" enctype="multipart/form-data" action="{{route('admin.content.update')}}" class="pg-admin-card form-card wide">@csrf @method('patch')
<div class="form-grid"><label>Brand name<input name="brand_name" value="{{old('brand_name',$content['brand_name'])}}" required></label><label>Logo URL<input name="logo_url" value="{{old('logo_url',$content['logo_url'])}}"></label><label>Or upload Private Gather logo<input type="file" name="logo_image" accept="image/*"></label><label>Header join label<input name="header_cta_label" value="{{old('header_cta_label',$content['header_cta_label'])}}"></label><label class="span2">Header join URL<input name="header_cta_url" value="{{old('header_cta_url',$content['header_cta_url'])}}"></label>
<label>Hero eyebrow<input name="hero_eyebrow" value="{{old('hero_eyebrow',$content['hero_eyebrow'])}}"></label><label>Hero heading<input name="hero_heading" value="{{old('hero_heading',$content['hero_heading'])}}"></label><label class="span2">Hero body<textarea name="hero_body" rows="4">{{old('hero_body',$content['hero_body'])}}</textarea></label><label>Hero image URL (optional)<input name="hero_image_url" value="{{old('hero_image_url',$content['hero_image_url'])}}"></label><label>Or upload hero image<input type="file" name="hero_image" accept="image/*"></label><label>Primary button label<input name="hero_primary_label" value="{{old('hero_primary_label',$content['hero_primary_label'])}}"></label><label>Primary button URL<input name="hero_primary_url" value="{{old('hero_primary_url',$content['hero_primary_url'])}}"></label><label>Secondary button label<input name="hero_secondary_label" value="{{old('hero_secondary_label',$content['hero_secondary_label'])}}"></label><label>Secondary button URL<input name="hero_secondary_url" value="{{old('hero_secondary_url',$content['hero_secondary_url'])}}"></label>
<label>Featured eyebrow<input name="featured_eyebrow" value="{{old('featured_eyebrow',$content['featured_eyebrow'])}}"></label><label>Featured heading<input name="featured_heading" value="{{old('featured_heading',$content['featured_heading'])}}"></label><label>Organizations eyebrow<input name="organizations_eyebrow" value="{{old('organizations_eyebrow',$content['organizations_eyebrow'])}}"></label><label>Organizations heading<input name="organizations_heading" value="{{old('organizations_heading',$content['organizations_heading'])}}"></label><label>Domain eyebrow<input name="domain_eyebrow" value="{{old('domain_eyebrow',$content['domain_eyebrow'])}}"></label><label>Domain heading<input name="domain_heading" value="{{old('domain_heading',$content['domain_heading'])}}"></label><label class="span2">Domain section text<textarea name="domain_body" rows="3">{{old('domain_body',$content['domain_body'])}}</textarea></label><label class="span2">Footer text<textarea name="footer_text" rows="3">{{old('footer_text',$content['footer_text'])}}</textarea></label><label>About heading<input name="about_heading" value="{{old('about_heading',$content['about_heading'])}}"></label><label>About image URL<input name="about_image_url" value="{{old('about_image_url',$content['about_image_url'])}}"></label><label>Or upload about image<input type="file" name="about_image" accept="image/*"></label><label class="span2">About text<textarea name="about_body" rows="6">{{old('about_body',$content['about_body'])}}</textarea></label></div>
<div class="row-actions"><label class="checkbox-line"><input type="checkbox" name="show_featured_events" value="1" @checked(($content['show_featured_events']??'1')==='1')> Show featured events</label><label class="checkbox-line"><input type="checkbox" name="show_organizations" value="1" @checked(($content['show_organizations']??'1')==='1')> Show organizations</label><label class="checkbox-line"><input type="checkbox" name="show_domain_section" value="1" @checked(($content['show_domain_section']??'1')==='1')> Show custom-domain section</label></div>@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif<button type="submit">Save Website</button></form>
@endsection
