@extends('layouts.app')
@section('title',$section==='trust'?'Trust & Safety':'Platform Insights')
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">PLATFORM ADMIN</span><h1>{{$section==='trust'?'Trust & Safety operations':'Private Gather network intelligence'}}</h1><p>{{$section==='trust'?'Prioritize real reports and verification concerns without exposing private evidence or turning members into public reputation scores.':'Measure growth, marketplace activity, platform fees, markets and production readiness from one decision surface.'}}</p><nav class="pc-chip-row" aria-label="Platform operations"><a href="{{route('admin.insights.index')}}">Insights</a><a href="{{route('admin.trust.index')}}">Trust & Safety</a><a href="{{route('admin.moderation.index')}}">Moderation</a><a href="{{route('admin.health.index')}}">System Health</a></nav></div></section>
<section class="pg-page"><div class="pg-shell">@if(session('status'))<div class="success" role="status">{{session('status')}}</div>@endif @if($errors->any())<div class="error" role="alert">{{$errors->first()}}</div>@endif
@if($section==='analytics')
<div class="pg-grid pg-grid-4">@foreach(['users'=>'Users','active_users'=>'Active users','clubs'=>'Organizations','upcoming_events'=>'Upcoming events','connections'=>'Connections','reviews'=>'Reviews','campaigns'=>'Campaigns','referrals'=>'Referral conversions'] as $key=>$label)<div class="pg-stat"><span>{{$label}}</span><strong>{{$metrics[$key]}}</strong></div>@endforeach</div>
<section class="pg-section pc-two"><div class="pg-card"><span class="pg-eyebrow">MARKETPLACE ECONOMICS</span><h2>GMV & platform fees</h2><div class="row-between"><div><span class="muted">Gross ticket volume represented in ledger</span><div class="pc-kpi">${{number_format($metrics['gross_cents']/100,2)}}</div></div><div><span class="muted">Platform fees</span><div class="pc-kpi">${{number_format($metrics['fee_cents']/100,2)}}</div></div></div></div><div class="pg-card"><span class="pg-eyebrow">PRODUCTION READINESS</span><h2>Operational checks</h2><div class="pc-status-grid">@foreach($readiness as $key=>$ok)<div class="pc-status"><strong>{{$ok?'Ready':'Needs setup'}}</strong><small>{{str_replace('_',' ',$key)}}</small></div>@endforeach</div></div></section>
<section class="pg-section pc-two"><div class="pg-card"><h2>Active markets</h2>@forelse($markets as $market)<div class="row-between"><span>{{$market->city}}</span><strong>{{$market->total}} events</strong></div>@empty<div class="pg-empty">No published market data yet.</div>@endforelse</div><div class="pg-card"><span class="pg-eyebrow">WHAT TO WATCH</span><h2>Launch health</h2><p class="muted">Use System Health for service-level diagnostics. This screen is the product/business layer: acquisition, activity, commerce and regional growth.</p><a class="button button-ghost" href="{{route('admin.health.index')}}">Open System Health</a></div></section>
@else
<div class="pg-grid pg-grid-4"><div class="pg-stat"><span>Open moderation reports</span><strong>{{$openReports}}</strong></div><div class="pg-stat"><span>Pending verification reviews</span><strong>{{$pendingVerifications->count()}}</strong></div><div class="pg-stat"><span>Member blocks</span><strong>{{$blocks}}</strong></div><div class="pg-stat"><span>Trust cases</span><strong>{{$cases->total()}}</strong></div></div>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">ESCALATION QUEUE</span><h2>Reports not yet linked to a trust case</h2><p>Escalating creates an auditable case and assigns the report for review.</p></div></div><div class="pg-grid pg-grid-2">@forelse($unlinkedReports as $report)<article class="pg-card"><div class="row-between"><div><span class="pg-pill">{{ucfirst($report->category)}}</span><h3>Moderation report #{{$report->id}}</h3><p class="muted">{{$report->details?\Illuminate\Support\Str::limit($report->details,220):'No additional report detail.'}}</p></div></div><form method="post" action="{{route('admin.trust.report.escalate',$report->id)}}" class="form-inline">@csrf<label>Priority<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><button class="button button-primary">Escalate</button></form></article>@empty<div class="pg-empty">All open/reviewing moderation reports are already linked or the queue is empty.</div>@endforelse</div></section>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">VERIFICATION REVIEW</span><h2>Status-only trust escalation</h2><p>Provider references and status can be used operationally. Raw identity documents and provider evidence are never copied into trust-case notes.</p></div></div><div class="pg-grid pg-grid-2">@forelse($pendingVerifications as $verification)<article class="pg-card"><div class="row-between"><div><div class="pg-event-meta"><span class="pg-pill">{{ucfirst($verification->status)}}</span><span class="pg-pill">{{ucfirst(str_replace('_',' ',$verification->type))}}</span></div><h3>{{$verification->user?->display_name?:$verification->user?->name?:'Account verification'}}</h3><p class="muted">Verification #{{$verification->id}} · provider {{$verification->provider?:'manual'}} @if($verification->expires_at) · expires {{$verification->expires_at->format('M j, Y')}} @endif</p></div></div><form method="post" action="{{route('admin.trust.verification.escalate',$verification)}}" class="form-inline">@csrf<label>Priority<select name="priority"><option value="{{$verification->status==='failed'?'high':'normal'}}">Recommended: {{$verification->status==='failed'?'High':'Normal'}}</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></label><button class="button button-ghost">Escalate safely</button></form></article>@empty<div class="pg-empty">No pending, reviewing or failed verification records.</div>@endforelse</div></section>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">CASE WORK</span><h2>Trust & Safety cases</h2></div></div><div class="pg-grid">@forelse($cases as $case)<form method="post" action="{{route('admin.trust.update',$case->id)}}" class="pg-card">@csrf @method('PATCH')<div class="row-between"><div><div class="pg-event-meta"><span class="pg-pill">{{strtoupper($case->priority)}}</span><span class="pg-pill">{{ucfirst($case->status)}}</span></div><h3>{{str_replace('_',' ',ucfirst($case->type))}}</h3><p class="muted">Subject: {{$case->subject_name?:'Account/organization context'}} · opened {{\Carbon\Carbon::parse($case->created_at)->diffForHumans()}} @if($case->report_id) · report #{{$case->report_id}} @endif</p>@if($case->notes)<div class="pg-privacy-note">{{$case->notes}}</div>@endif</div><div class="form-inline"><select name="priority" aria-label="Case priority">@foreach(['low','normal','high','urgent'] as $p)<option value="{{$p}}" @selected($case->priority===$p)>{{ucfirst($p)}}</option>@endforeach</select><select name="status" aria-label="Case status">@foreach(['open','reviewing','resolved','dismissed'] as $s)<option value="{{$s}}" @selected($case->status===$s)>{{ucfirst($s)}}</option>@endforeach</select></div></div><label style="margin-top:12px">Resolution / case note<textarea name="resolution" rows="3" maxlength="5000">{{$case->resolution}}</textarea></label><button class="button button-primary" style="margin-top:10px">Save case</button></form>@empty<div class="pg-empty"><h2>No trust cases</h2><p>Cases appear here when escalated from moderation or verification workflows.</p></div>@endforelse</div>{{$cases->links()}}</section>
@endif
</div></section>
@endsection
