@extends('layouts.app')
@section('title',$section==='trust'?'Trust & Safety':'Platform Insights')
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">PLATFORM ADMIN</span><h1>{{$section==='trust'?'Trust & Safety operations':'Private Gather network intelligence'}}</h1><p>{{$section==='trust'?'Prioritize real reports, verification concerns and appeals without turning private member data into a public score.':'Measure growth, marketplace activity, platform fees, markets and production readiness from one decision surface.'}}</p><div class="pc-chip-row"><a href="{{route('admin.insights.index')}}">Insights</a><a href="{{route('admin.trust.index')}}">Trust & Safety</a><a href="{{route('admin.moderation.index')}}">Moderation</a><a href="{{route('admin.health.index')}}">System Health</a></div></div></section>
<section class="pg-page"><div class="pg-shell">
@if($section==='analytics')<div class="pg-grid pg-grid-4">@foreach(['users'=>'Users','active_users'=>'Active users','clubs'=>'Organizations','upcoming_events'=>'Upcoming events','connections'=>'Connections','reviews'=>'Reviews','campaigns'=>'Campaigns','referrals'=>'Referral conversions'] as $key=>$label)<div class="pg-stat"><span>{{$label}}</span><strong>{{$metrics[$key]}}</strong></div>@endforeach</div><section class="pg-section pc-two"><div class="pg-card"><span class="pg-eyebrow">MARKETPLACE ECONOMICS</span><h2>GMV & platform fees</h2><div class="row-between"><div><span class="muted">Gross ticket volume represented in ledger</span><div class="pc-kpi">${{number_format($metrics['gross_cents']/100,2)}}</div></div><div><span class="muted">Platform fees</span><div class="pc-kpi">${{number_format($metrics['fee_cents']/100,2)}}</div></div></div></div><div class="pg-card"><span class="pg-eyebrow">PRODUCTION READINESS</span><h2>Operational checks</h2><div class="pc-status-grid">@foreach($readiness as $key=>$ok)<div class="pc-status"><strong>{{$ok?'Ready':'Needs setup'}}</strong><small>{{str_replace('_',' ',$key)}}</small></div>@endforeach</div></div></section><section class="pg-section pc-two"><div class="pg-card"><h2>Active markets</h2>@foreach($markets as $market)<div class="row-between"><span>{{$market->city}}</span><strong>{{$market->total}} events</strong></div>@endforeach</div><div class="pg-card"><span class="pg-eyebrow">WHAT TO WATCH</span><h2>Launch health</h2><p class="muted">Use System Health for service-level diagnostics. This screen is the product/business layer: acquisition, activity, commerce and regional growth.</p><a class="button button-ghost" href="{{route('admin.health.index')}}">Open System Health</a></div></section>
@else<div class="pg-grid pg-grid-3"><div class="pg-stat"><span>Open moderation reports</span><strong>{{$openReports}}</strong></div><div class="pg-stat"><span>Member blocks</span><strong>{{$blocks}}</strong></div><div class="pg-stat"><span>Trust cases shown</span><strong>{{$cases->total()}}</strong></div></div><section class="pg-section"><div class="pg-grid">@forelse($cases as $case)<form method="post" action="{{route('admin.trust.update',$case->id)}}" class="pg-card">@csrf @method('PATCH')<div class="row-between"><div><div class="pg-event-meta"><span class="pg-pill">{{strtoupper($case->priority)}}</span><span class="pg-pill">{{ucfirst($case->status)}}</span></div><h3>{{str_replace('_',' ',ucfirst($case->type))}}</h3><p class="muted">Subject: {{$case->subject_name?:'Account/organization context'}} · opened {{\Carbon\Carbon::parse($case->created_at)->diffForHumans()}}</p></div><div class="form-inline"><select name="priority">@foreach(['low','normal','high','urgent'] as $p)<option value="{{$p}}" @selected($case->priority===$p)>{{ucfirst($p)}}</option>@endforeach</select><select name="status">@foreach(['open','reviewing','resolved','dismissed'] as $s)<option value="{{$s}}" @selected($case->status===$s)>{{ucfirst($s)}}</option>@endforeach</select></div></div><label style="margin-top:12px">Resolution / case note<textarea name="resolution" rows="3">{{$case->resolution}}</textarea></label><button class="button button-primary" style="margin-top:10px">Save case</button></form>@empty<div class="pg-empty"><h2>No trust cases</h2><p>Cases appear here when escalated from moderation, verification or safety workflows.</p></div>@endforelse</div>{{$cases->links()}}</section>@endif
</div></section>
@endsection
