<?php

declare(strict_types=1);
namespace App\Http\Controllers\Member;
use App\Http\Controllers\Controller;use App\Models\ClubReward;use App\Models\MemberPointLedger;use App\Models\RewardRedemption;use App\Tenancy\TenantContext;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\View\View;
final class RewardController{
 public function index(Request $request,TenantContext $context):View{$tenant=$context->requireTenant();$user=$request->user();$balance=(int)MemberPointLedger::where('tenant_id',$tenant->id)->where('user_id',$user->id)->sum('points');$rewards=ClubReward::where('tenant_id',$tenant->id)->where('active',true)->orderBy('points_cost')->get();$redemptions=RewardRedemption::where('tenant_id',$tenant->id)->where('user_id',$user->id)->with('reward')->latest()->limit(20)->get();$membership=$tenant->users()->whereKey($user->id)->first()?->pivot;$memberCode=$this->memberCode((int)$tenant->id,(int)$user->id);return view('member.rewards',compact('tenant','user','balance','rewards','redemptions','membership','memberCode'));}
 public function redeem(Request $request,TenantContext $context,ClubReward $reward):RedirectResponse{$tenant=$context->requireTenant();abort_unless((int)$reward->tenant_id===(int)$tenant->id&&$reward->active,404);DB::transaction(function()use($request,$tenant,$reward):void{$balance=(int)MemberPointLedger::where('tenant_id',$tenant->id)->where('user_id',$request->user()->id)->lockForUpdate()->sum('points');abort_if($balance<$reward->points_cost,422,'You do not have enough club points for this reward.');if($reward->inventory!==null)abort_if($reward->inventory<1,422,'This reward is currently unavailable.');$redemption=RewardRedemption::create(['tenant_id'=>$tenant->id,'reward_id'=>$reward->id,'user_id'=>$request->user()->id,'points_spent'=>$reward->points_cost,'status'=>'pending']);MemberPointLedger::create(['tenant_id'=>$tenant->id,'user_id'=>$request->user()->id,'points'=>-$reward->points_cost,'reason'=>'Reward redemption: '.$reward->name,'source_type'=>'reward_redemption','source_id'=>$redemption->id]);if($reward->inventory!==null)$reward->decrement('inventory');});return back()->with('status','Reward requested. Club staff can now fulfill it.');}
 private function memberCode(int $tenantId,int $userId):string{return 'PG-'.str_pad((string)$tenantId,4,'0',STR_PAD_LEFT).'-'.str_pad((string)$userId,6,'0',STR_PAD_LEFT).'-'.strtoupper(substr(hash_hmac('sha256',$tenantId.':'.$userId,(string)config('app.key')),0,8));}
}
