@extends('layouts.app')
@section('title','Branding & Theme')
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">CLUB OS · BRANDING</span><h1>{{$tenant->name}} website identity</h1><p>Choose a tenant-only website theme, then layer your own logo, colors and typography on top. Tenant themes are deliberately separate from Private Gather’s central-site themes so your club site feels like its own destination.</p></div></section>
<section class="pg-page"><div class="pg-shell"><form class="pg-card form-stack" method="post" action="{{route('tenant.branding.update')}}">@csrf @method('patch')
<section><span class="pg-eyebrow">TENANT WEBSITE THEME</span><h2>Choose a full layout</h2><p class="muted">These presets change header architecture, navigation placement, hero composition, spacing, card geometry, section rhythm and typography—not only colors.</p><div class="pg-grid pg-grid-2">@foreach($tenantThemes as $key=>$theme)<label class="pg-card pg-card-interactive" style="cursor:pointer"><span class="row-actions"><input type="radio" name="theme_preset" value="{{$key}}" @checked(old('theme_preset',$activeTheme)===$key)><strong>{{$theme['label']}}</strong></span><small class="muted">{{$theme['description']}}</small><span class="pg-pill" style="margin-top:12px">Layout: {{ucwords(str_replace('_',' ',$theme['layout']))}}</span></label>@endforeach</div></section>
<section style="margin-top:18px"><span class="pg-eyebrow">YOUR BRAND</span><h2>Logo, colors & type</h2><p class="muted">Use URLs from the Media Library for logo/favicon fields, or another HTTPS asset URL.</p><div class="form-grid"><label class="span2">Logo URL / path<input name="logo_path" value="{{old('logo_path',$branding->logo_path)}}" placeholder="/uploads/... or https://..."></label><label class="span2">Favicon URL / path<input name="favicon_path" value="{{old('favicon_path',$branding->favicon_path)}}"></label><label>Primary color<input name="primary_color" value="{{old('primary_color',$branding->primary_color)}}" placeholder="#d7b56d"></label><label>Accent color<input name="accent_color" value="{{old('accent_color',$branding->accent_color)}}" placeholder="#7d3b69"></label><label>Font family<input name="font_family" value="{{old('font_family',$branding->font_family)}}" placeholder="Inter"></label><label>Email sender name<input name="email_from_name" value="{{old('email_from_name',$branding->email_from_name)}}"></label></div></section>
<label class="row-actions"><input type="checkbox" name="show_platform_branding" value="1" @checked($branding->show_platform_branding)><span><strong>Show “Powered by Private Gather”</strong><br><small class="muted">This does not make your tenant site use the Private Gather main-site theme.</small></span></label>
@if($errors->any())<div class="error">{{$errors->first()}}</div>@endif<button class="button button-primary">Save Branding & Theme</button></form></div></section>
@endsection
