@extends('layouts.app')
@section('title','Branding & Theme')
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">CLUB OS · BRANDING</span><h1>{{$tenant->name}} website identity</h1><p>Choose a tenant-only website theme, preview its real layout character, then layer your own logo, colors and typography on top. Tenant themes remain deliberately separate from the central Private Gather marketplace.</p></div></section>
<section class="pg-page"><div class="pg-shell"><form class="pg-card form-stack" method="post" action="{{route('tenant.branding.update')}}">@csrf @method('patch')
<section><div class="pg-section-head"><div><span class="pg-eyebrow">TENANT WEBSITE THEME</span><h2>Ten genuinely different starting points</h2><p>Preview desktop, tablet or mobile proportions before activation. Presets change shell architecture, navigation placement, hero composition, spacing, cards and typography—not only color.</p></div><div class="pc-segment" data-preview-size><button type="button" data-size="desktop" class="is-active">Desktop</button><button type="button" data-size="tablet">Tablet</button><button type="button" data-size="mobile">Mobile</button></div></div><div class="pg-grid pg-grid-2">@foreach($tenantThemes as $key=>$theme)<label class="pc-theme-card" data-theme-card="{{$key}}"><span class="row-actions"><input type="radio" name="theme_preset" value="{{$key}}" @checked(old('theme_preset',$activeTheme)===$key)><strong>{{$theme['label']}}</strong></span><div class="pc-theme-preview pc-preview-{{$theme['preview']}}"><div class="pc-preview-nav"></div><div class="pc-preview-hero"><span></span><strong>{{$tenant->name}}</strong></div><div class="pc-preview-cards"><i></i><i></i><i></i></div></div><small class="muted">{{$theme['description']}}</small><span class="pg-pill">Layout: {{ucwords(str_replace('_',' ',$theme['layout']))}}</span></label>@endforeach</div></section>
<section style="margin-top:24px"><span class="pg-eyebrow">YOUR BRAND</span><h2>Logo, colors & type</h2><p class="muted">Use assets from the Media Library for the best privacy and delivery control.</p><div class="form-grid"><label class="span2">Logo URL / path<input name="logo_path" value="{{old('logo_path',$branding->logo_path)}}" placeholder="/uploads/... or https://..."></label><label class="span2">Favicon URL / path<input name="favicon_path" value="{{old('favicon_path',$branding->favicon_path)}}"></label><label>Primary color<input name="primary_color" value="{{old('primary_color',$branding->primary_color)}}" placeholder="#d7b56d"></label><label>Accent color<input name="accent_color" value="{{old('accent_color',$branding->accent_color)}}" placeholder="#7d3b69"></label><label>Font family<input name="font_family" value="{{old('font_family',$branding->font_family)}}" placeholder="Inter"></label><label>Email sender name<input name="email_from_name" value="{{old('email_from_name',$branding->email_from_name)}}"></label></div></section>
<label class="row-actions"><input type="checkbox" name="show_platform_branding" value="1" @checked($branding->show_platform_branding)><span><strong>Show “Powered by Private Gather”</strong><br><small class="muted">This does not make the tenant site use a Private Gather marketplace theme.</small></span></label>
@if($errors->any())<div class="error">{{$errors->first()}}</div>@endif<div class="pg-actions"><button class="button button-primary">Save Branding & Theme</button><a class="button button-ghost" target="_blank" rel="noopener" href="{{route('site.home')}}">Open live tenant site</a></div></form></div></section>
<script>(()=>{const host=document.querySelector('.pg-grid.pg-grid-2'),controls=document.querySelectorAll('[data-size]');controls.forEach(b=>b.addEventListener('click',()=>{controls.forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');host?.setAttribute('data-preview-mode',b.dataset.size);}));})();</script>
@endsection
