@extends('layouts.app')
@section('title','Community & Members · '.$tenant->name)
@section('content')
<section class="container section pg-suite-shell">
    <div class="pg-suite-pagehead"><div><span class="eyebrow">CLUB COMMUNITY ADMIN</span><h1>Community & Members</h1><p>Approve applications, manage member access, award trust badges, review reports and control the private community.</p></div><div class="row-actions"><a class="button button-ghost" href="{{ route('tenant.dashboard') }}">Manage Home</a><a class="button button-primary" href="{{ route('community.index') }}">Open Community</a></div></div>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif

    <div class="pg-suite-admin-grid">
        <section class="panel"><span class="eyebrow">COMMUNITY SETTINGS</span><h2>Member experience</h2><form class="form-stack" method="post" action="{{ route('tenant.community.settings') }}">@csrf @method('PATCH')
            @php($settings=$tenant->settings??[])
            <label>New registrations<select name="membership_registration"><option value="approval" @selected(($settings['membership_registration']??'approval')==='approval')>Application + club approval</option><option value="open" @selected(($settings['membership_registration']??'approval')==='open')>Join immediately</option></select></label>
            <label class="check"><input type="checkbox" name="community_wall" value="1" @checked($settings['community_wall']??true)> Enable club wall</label>
            <label class="check"><input type="checkbox" name="member_video_uploads" value="1" @checked($settings['member_video_uploads']??true)> Allow member video uploads</label>
            <label class="check"><input type="checkbox" name="member_directory" value="1" @checked($settings['member_directory']??true)> Enable member directory</label>
            <label class="check"><input type="checkbox" name="stories_enabled" value="1" @checked($settings['stories_enabled']??true)> Enable 24-hour member stories</label>
            <label class="check"><input type="checkbox" name="groups_enabled" value="1" @checked($settings['groups_enabled']??true)> Enable private member groups</label>
            <label class="check"><input type="checkbox" name="event_community" value="1" @checked($settings['event_community']??true)> Enable event-specific communities</label>
            <button class="button button-primary">Save Community Settings</button>
        </form></section>
        <section class="panel"><span class="eyebrow">WEBSITE & CONTENT</span><h2>Build the club site</h2><p class="muted">Website Builder sections can pull events, members, membership levels, news and the private community directly into your branded club site.</p><div class="pg-quick-grid"><a href="{{ route('tenant.cms.pages') }}">Website Builder</a><a href="{{ route('tenant.community.news') }}">News & Blog</a><a href="{{ route('tenant.events.index') }}">Events</a><a href="{{ route('tenant.branding.edit') }}">Branding</a></div></section>
    </div>

    <section class="panel pg-suite-admin-section"><div class="panel-head"><div><span class="eyebrow">APPLICATIONS</span><h2>Membership applications</h2></div><strong>{{ $applications->total() }}</strong></div>
        <div class="pg-admin-card-list">@forelse($applications as $application)<article class="pg-admin-member"><div><strong>{{ $application->user?->display_name ?: $application->user?->name }}</strong><small>{{ ucfirst($application->status) }} · {{ $application->created_at->diffForHumans() }}</small>@if($application->user?->profile)<p>{{ $application->user->profile->headline ?: ucfirst(str_replace('_',' ',$application->user->profile->lifestyle_identity??'member')) }}</p>@endif @if($application->member_note)<p class="muted">Application: {{ $application->member_note }}</p>@endif</div>@if($application->status==='pending')<form class="pg-review-form" method="post" action="{{ route('tenant.community.applications.review',$application) }}">@csrf @method('PATCH')<textarea name="review_note" rows="2" placeholder="Optional private review note"></textarea><div class="row-actions"><button class="button button-primary" name="decision" value="approve">Approve</button><button class="button button-ghost" name="decision" value="decline">Decline</button></div></form>@endif</article>@empty<p class="muted">No membership applications yet.</p>@endforelse</div>{{ $applications->links() }}
    </section>

    <section class="panel pg-suite-admin-section"><div class="panel-head"><div><span class="eyebrow">MEMBERSHIP CARD</span><h2>Verify a member code</h2></div></div><div class="pg-suite-admin-grid"><form class="form-stack" method="post" action="{{ route('tenant.community.member-card.verify') }}">@csrf<label>Member code<input name="member_code" required maxlength="80" placeholder="PG-0001-000123-ABC12345"></label><button class="button button-primary">Verify Membership</button></form>@if(session('member_card_verification')) @php($verified=session('member_card_verification'))<div class="panel pg-verified-member"><span class="eyebrow">VERIFIED RESULT</span><h3>{{ $verified['name'] }}</h3><p><strong>{{ ucfirst($verified['status']) }}</strong> membership · {{ ucfirst($verified['role']) }} · Member #{{ $verified['user_id'] }}</p></div>@else<div><p class="muted">Members can show the club-specific code from their client-area Membership Card. Verification checks the signed code against this club and the current membership record.</p></div>@endif</div></section>

    <section class="panel pg-suite-admin-section"><div class="panel-head"><div><span class="eyebrow">MEMBERS</span><h2>Club member directory</h2></div><strong>{{ $members->total() }}</strong></div>
        <div class="pg-admin-card-list">@forelse($members as $member)<article class="pg-admin-member"><div><a href="{{ route('members.show',$member) }}"><strong>{{ $member->display_name ?: $member->name }}</strong></a><small>{{ ucfirst($member->pivot->status) }} · {{ ucfirst($member->pivot->role) }}</small><p>{{ $member->profile?->headline ?: ucfirst(str_replace('_',' ',$member->profile?->lifestyle_identity??'member')) }}</p>@if($member->badges->isNotEmpty())<div class="pg-badges">@foreach($member->badges as $badge)<span>{{ $badge->icon ?: '◆' }} {{ $badge->label }}</span>@endforeach</div>@endif</div><div class="pg-member-admin-actions"><form method="post" action="{{ route('tenant.community.members.status',$member) }}">@csrf @method('PATCH')<select name="status"><option value="active" @selected($member->pivot->status==='active')>Active</option><option value="pending" @selected($member->pivot->status==='pending')>Pending</option><option value="suspended" @selected($member->pivot->status==='suspended')>Suspended</option><option value="banned" @selected($member->pivot->status==='banned')>Banned</option></select><button class="btn">Update</button></form><details><summary>Adjust points</summary><form class="form-stack" method="post" action="{{ route('tenant.community.members.points',$member) }}">@csrf<label>Points <small>Use a negative number to deduct.</small><input type="number" name="points" required></label><label>Reason<input name="reason" maxlength="190" required></label><button class="btn">Apply Points</button></form></details><details><summary>Award badge</summary><form class="form-stack" method="post" action="{{ route('tenant.community.members.badges',$member) }}">@csrf<label>Code<input name="code" maxlength="80" required placeholder="verified"></label><label>Label<input name="label" maxlength="120" required placeholder="Verified Member"></label><label>Icon<input name="icon" maxlength="40" placeholder="✓"></label><label>Visibility<select name="visibility"><option value="members">Members</option><option value="connections">Connections</option><option value="private">Private</option></select></label><button class="btn">Save Badge</button></form></details></div></article>@empty<p class="muted">No members yet.</p>@endforelse</div>{{ $members->links() }}
    </section>

    <section class="panel pg-suite-admin-section"><div class="panel-head"><div><span class="eyebrow">LOYALTY & REWARDS</span><h2>Club points</h2></div><strong>{{ $rewards->count() }} rewards</strong></div><div class="pg-suite-admin-grid"><form class="form-stack" method="post" action="{{ route('tenant.community.rewards.store') }}">@csrf<h3>Create reward</h3><label>Name<input name="name" maxlength="160" required></label><label>Description<textarea name="description" rows="2"></textarea></label><div class="form-grid"><label>Points cost<input type="number" name="points_cost" min="1" required></label><label>Inventory <small>blank = unlimited</small><input type="number" name="inventory" min="0"></label></div><button class="button button-primary">Create Reward</button></form><div><h3>Published rewards</h3>@forelse($rewards as $reward)<div class="pg-dashboard-row"><div><strong>{{ $reward->name }}</strong><small>{{ number_format($reward->points_cost) }} points @if($reward->inventory!==null) · {{ $reward->inventory }} remaining @endif</small></div></div>@empty<p class="muted">No rewards yet.</p>@endforelse</div></div>@if($redemptions->isNotEmpty())<hr><h3>Pending redemptions</h3>@foreach($redemptions as $redemption)<article class="pg-report-row"><div><strong>{{ $redemption->user?->display_name ?: $redemption->user?->name }} — {{ $redemption->reward?->name }}</strong><small>{{ number_format($redemption->points_spent) }} points · {{ $redemption->created_at->diffForHumans() }}</small></div><form method="post" action="{{ route('tenant.community.redemptions.update',$redemption) }}">@csrf @method('PATCH')<select name="status"><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancel & refund</option></select><button class="btn">Update</button></form></article>@endforeach @endif</section>

    <section class="panel pg-suite-admin-section"><div class="panel-head"><div><span class="eyebrow">MODERATION</span><h2>Open community reports</h2></div><strong>{{ $reports->count() }}</strong></div>@forelse($reports as $report)<article class="pg-report-row"><div><strong>{{ ucfirst(str_replace('_',' ',$report->category)) }}</strong><small>{{ $report->reportable_type }} #{{ $report->reportable_id }} · reported by {{ $report->reporter?->display_name ?: $report->reporter?->name ?: 'Member' }}</small><p>{{ $report->details }}</p></div><form method="post" action="{{ route('tenant.community.reports.update',$report) }}">@csrf @method('PATCH')<select name="status"><option value="open" @selected($report->status==='open')>Open</option><option value="reviewing" @selected($report->status==='reviewing')>Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><button class="btn">Save</button></form></article>@empty<p class="muted">No open reports.</p>@endforelse</section>
</section>
@endsection
