@extends('layouts.app')
@section('title','Commerce & Payouts · '.$tenant->name)
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">CLUB OS · COMMERCE</span><h1>Money in, fees clear, access accounted for.</h1><p>Ticket sales, platform fees, membership billing state, refunds and payouts share one tenant-scoped ledger. Provider state is explicit—Private Gather never calls a pending external charge paid.</p><nav class="pc-chip-row" aria-label="Club OS"><a href="{{route('tenant.crm.index')}}">CRM</a><a href="{{route('tenant.commerce.index')}}">Commerce</a><a href="{{route('tenant.domain-marketplace.index')}}">Domains</a><a href="{{route('tenant.builder.index')}}">Website Builder</a><a href="{{route('tenant.growth.index')}}">Growth</a><a href="{{route('tenant.analytics.index')}}">Analytics</a></nav></div></section>
<section class="pg-page"><div class="pg-shell">
@if(session('status'))<div class="success" role="status">{{session('status')}}</div>@endif
@if($errors->any())<div class="error" role="alert">{{$errors->first()}}</div>@endif

<div class="pg-grid pg-grid-4"><div class="pg-stat"><span>Gross ticket revenue</span><strong>${{number_format($gross/100,2)}}</strong></div><div class="pg-stat"><span>Platform fees</span><strong>${{number_format($fees/100,2)}}</strong></div><div class="pg-stat"><span>Club net posted</span><strong>${{number_format($net/100,2)}}</strong></div><div class="pg-stat"><span>Available payout</span><strong>${{number_format($available/100,2)}}</strong></div></div>

<section class="pg-section"><div class="pc-two"><form method="post" action="{{route('tenant.commerce.merchant')}}" class="pg-card form-stack">@csrf @method('PATCH')<span class="pg-eyebrow">MERCHANT CONNECTION</span><h2>Provider state</h2><label>Provider<input name="provider" value="{{old('provider',$merchant?->provider??'manual')}}" placeholder="Provider adapter name" required></label><label>Connected account reference<input name="provider_account_ref" value="{{old('provider_account_ref',$merchant?->provider_account_ref)}}" placeholder="Provider account ID — never a secret key"></label><label>Status<select name="status">@foreach(['not_connected','pending','connected','restricted'] as $state)<option value="{{$state}}" @selected(old('status',$merchant?->status??'not_connected')===$state)>{{ucfirst(str_replace('_',' ',$state))}}</option>@endforeach</select></label><button class="button button-primary">Save connection state</button><div class="pg-privacy-note">API credentials stay in server configuration. This screen stores only non-secret provider/account state.</div></form>
<form method="post" action="{{route('tenant.commerce.payouts.store')}}" class="pg-card form-stack">@csrf<span class="pg-eyebrow">PAYOUT</span><h2>Request available funds</h2><label>Amount in cents<input name="amount_cents" type="number" min="100" max="{{$available}}" value="{{$available}}" required></label><button class="button button-primary" @disabled($available<100)>Request payout</button><p class="muted">Requested, processing and paid payouts reserve balance immediately so the same funds cannot be requested twice.</p></form></div></section>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">MEMBERSHIP BILLING</span><h2>Subscriptions & access terms</h2><p>Create complimentary terms or prepare recurring memberships for the configured provider.</p></div></div><div class="pc-two"><form method="post" action="{{route('tenant.commerce.subscriptions.store')}}" class="pg-card form-stack">@csrf<label>Member<select name="user_id" required><option value="">Choose member</option>@foreach($members as $member)<option value="{{$member->id}}">{{$member->display_name?:$member->name}}</option>@endforeach</select></label><label>Membership level<select name="membership_level_id" required><option value="">Choose level</option>@foreach($levels as $level)<option value="{{$level->id}}">{{$level->name}} · {{$level->priceLabel()}} · {{ucfirst($level->billing_interval)}}</option>@endforeach</select></label><label class="row-actions"><input type="checkbox" name="complimentary" value="1"> Complimentary / no external charge</label><button class="button button-primary" @disabled($members->isEmpty()||$levels->isEmpty())>Create membership term</button><small class="muted">A paid recurring term remains awaiting/pending provider until the external provider confirms billing. Complimentary/free terms can activate immediately.</small></form><aside class="pg-card"><span class="pg-eyebrow">BILLING BOUNDARY</span><h2>Access and payment are separate facts.</h2><p class="muted">Private Gather records the membership term, provider state, amount and current period independently. That keeps membership access auditable even when payment processing is delayed, restricted or manual.</p><a class="button button-ghost" href="{{route('tenant.membership-levels.index')}}">Manage membership levels</a></aside></div>
<div class="pg-grid" style="margin-top:16px">@forelse($subscriptions as $subscription)<article class="pg-card"><div class="row-between"><div><span class="pg-pill">{{ucfirst(str_replace('_',' ',$subscription->status))}}</span><h3>{{$subscription->display_name?:$subscription->user_name?:'Member'}} · {{$subscription->level_name?:'Membership'}}</h3><p class="muted">${{number_format($subscription->amount_cents/100,2)}} · {{ucfirst($subscription->billing_interval)}} · {{$subscription->provider}} @if($subscription->current_period_ends_at) · through {{\Carbon\Carbon::parse($subscription->current_period_ends_at)->format('M j, Y')}} @endif</p></div><div class="pg-actions">@if($subscription->cancel_at_period_end)<span class="pg-pill pg-pill-warn">Cancels at period end</span>@elseif(!in_array($subscription->status,['cancelled'],true))<form method="post" action="{{route('tenant.commerce.subscriptions.cancel',$subscription->id)}}">@csrf @method('PATCH')<button class="button button-ghost" data-confirm="Schedule this subscription to cancel at period end?">Cancel at period end</button></form>@endif @if(!in_array($subscription->status,['awaiting_provider','pending_provider'],true))<form method="post" action="{{route('tenant.commerce.subscriptions.renew',$subscription->id)}}">@csrf @method('PATCH')<button class="button button-ghost">Renew term</button></form>@endif</div></div></article>@empty<div class="pg-empty"><h3>No subscription records yet.</h3><p>Approved memberships can still exist without recurring billing.</p></div>@endforelse</div></section>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">SPLIT LEDGER</span><h2>Posted ticket-sale accounting</h2></div></div><div class="pg-card" style="overflow:auto"><table><thead><tr><th>Date</th><th>Order</th><th>Gross</th><th>Platform fee</th><th>Club net</th><th>Status</th></tr></thead><tbody>@forelse($ledger as $row)<tr><td>{{\Carbon\Carbon::parse($row->created_at)->format('M j, Y')}}</td><td>#{{$row->order_id}}</td><td>${{number_format($row->gross_cents/100,2)}}</td><td>${{number_format($row->platform_fee_cents/100,2)}}</td><td>${{number_format($row->tenant_net_cents/100,2)}}</td><td>{{$row->status}}</td></tr>@empty<tr><td colspan="6">Paid ticket orders will appear here.</td></tr>@endforelse</tbody></table></div>{{$ledger->links()}}</section>

<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">REFUNDS</span><h2>Paid orders</h2><p>Refunds remain tied to the tenant/order/payment and cannot exceed the paid order total.</p></div></div><div class="pg-grid pg-grid-2">@forelse($orders as $order)<article class="pg-card"><div class="row-between"><div><span class="pg-pill">Order #{{$order->id}}</span><h3>{{$order->event?->title?:'Event order'}}</h3><p class="muted">{{$order->user?->display_name?:$order->user?->name?:'Member'}} · ${{number_format($order->total_cents/100,2)}} · {{ucfirst($order->status)}}</p></div></div><form method="post" action="{{route('tenant.commerce.refunds.store',$order)}}" class="form-inline" style="margin-top:12px">@csrf<label>Refund cents<input name="amount_cents" type="number" min="1" max="{{$order->total_cents}}" required></label><label>Reason<input name="reason" maxlength="1000" placeholder="Optional internal reason"></label><button class="button button-ghost">Record / request refund</button></form></article>@empty<div class="pg-empty">No paid orders available for refund.</div>@endforelse</div></section>

<section class="pg-section"><div class="pg-grid pg-grid-2"><article class="pg-card"><span class="pg-eyebrow">PAYOUT HISTORY</span><h2>Recent requests</h2>@forelse($payouts as $payout)<div class="row-between"><div><strong>${{number_format($payout->amount_cents/100,2)}}</strong><small>{{ucfirst($payout->status)}} · {{\Carbon\Carbon::parse($payout->created_at)->format('M j, Y')}}</small></div><span class="pg-pill">{{$payout->provider_reference?:'Awaiting provider'}}</span></div>@empty<div class="pg-empty">No payouts requested.</div>@endforelse</article><article class="pg-card"><span class="pg-eyebrow">REFUND HISTORY</span><h2>Recent refunds</h2>@forelse($refunds as $refund)<div class="row-between"><div><strong>${{number_format($refund->amount_cents/100,2)}} · Order #{{$refund->order_id}}</strong><small>{{ucfirst(str_replace('_',' ',$refund->status))}} @if($refund->reason) · {{$refund->reason}} @endif</small></div></div>@empty<div class="pg-empty">No refunds recorded.</div>@endforelse</article></div></section>
</div></section>
@endsection
