@extends('layouts.app')
@section('title','Club OS — '.$tenant->name)
@section('content')
@php $primary=$tenant->domains->firstWhere('is_primary',true);$siteUrl=$primary?\App\Support\TenantUrl::to($primary):\App\Support\MountUrl::to('/');$isHosted=\App\Support\Edition::isHosted(); @endphp
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">{{ $isHosted ? 'CLUB OS' : 'PRIVATE COMMUNITY OPERATIONS' }}</span><h1>{{ $tenant->name }}</h1><p>{{ $isHosted ? 'Run memberships, events, admission, tickets, staff and your branded site without mixing operational data into the public member experience.' : 'Manage this private installation’s website, events, memberships, members and staff from one workspace.' }}</p><div class="pg-actions" style="margin-top:22px">@if($siteUrl)<a class="button button-primary" target="_blank" rel="noopener" href="{{ $siteUrl }}">Open {{ $isHosted ? 'club site' : 'site' }}</a>@endif @if($isHosted)<a class="button button-ghost" target="_blank" rel="noopener" href="{{ route('organizations.index',['preview'=>$tenant->id]) }}">Preview Website</a><a class="button button-ghost" href="{{ route('organizations.index') }}">My communities</a>@endif</div>@if($siteUrl)<p class="muted" style="margin-top:14px">Site address: <a class="text-link" target="_blank" rel="noopener" href="{{ $siteUrl }}">{{ $siteUrl }}</a></p>@endif</div></section>
<section class="pg-page"><div class="pg-shell">
<div class="pg-grid pg-grid-4"><div class="pg-stat"><span>Events</span><strong>{{ $tenant->events_count }}</strong></div>@if($isHosted)<div class="pg-stat"><span>Pending Applications</span><strong>{{ $tenant->pending_membership_applications_count }}</strong></div>@endif<div class="pg-stat"><span>Domains</span><strong>{{ $tenant->domains->count() }}</strong></div><div class="pg-stat"><span>{{ $isHosted?'Plan':'Edition' }}</span><strong style="font-size:1.6rem">{{ $isHosted?ucfirst($tenant->subscription?->plan?->name?:$tenant->plan):'Self-Hosted' }}</strong></div></div>
<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">TODAY</span><h2>Run the community</h2><p>High-frequency operator tasks stay up front.</p></div></div><div class="pg-grid pg-grid-3">
<a class="pg-card pg-card-interactive" href="{{ route('tenant.events.index') }}"><span class="pg-pill">Events</span><h3>Calendar & events</h3><p class="muted">Create experiences, manage attendees, admission rules and ticket inventory.</p></a>
@if($isHosted)<a class="pg-card pg-card-interactive" href="{{ route('tenant.membership-applications.index') }}"><span class="pg-pill pg-pill-warn">{{ $tenant->pending_membership_applications_count }} pending</span><h3>Membership applications</h3><p class="muted">Review prospective members without changing their global account.</p></a>@else<a class="pg-card pg-card-interactive" href="{{ route('tenant.members.index') }}"><span class="pg-pill">Membership</span><h3>Members & approvals</h3><p class="muted">Manage who belongs to this installation.</p></a>@endif
<a class="pg-card pg-card-interactive" href="{{ route('tenant.orders.index') }}"><span class="pg-pill">Commerce</span><h3>Orders</h3><p class="muted">Track event orders and payment state.</p></a>
<a class="pg-card pg-card-interactive" href="{{ route('tenant.staff.index') }}"><span class="pg-pill">Team</span><h3>Staff</h3><p class="muted">Keep operational access role-based and scoped to this organization.</p></a>
<a class="pg-card pg-card-interactive" href="{{ route('tenant.analytics.index') }}"><span class="pg-pill">Reports</span><h3>Analytics</h3><p class="muted">Understand event and operational activity.</p></a>
<a class="pg-card pg-card-interactive" href="{{ route('tenant.membership-levels.index') }}"><span class="pg-pill">Membership</span><h3>Levels & renewals</h3><p class="muted">Standard, VIP, annual, lifetime, couple and individual membership tiers.</p></a>
</div></section>
<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">COMMUNITY & BRAND</span><h2>Shape the experience</h2><p>Public presentation and private member operations stay connected but distinct.</p></div></div><div class="pg-grid pg-grid-4">
<a class="pg-card pg-card-interactive" href="{{ route('tenant.badges.index') }}"><h3>Badges</h3><p class="muted">Club-issued member recognition.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.cms.pages') }}"><h3>Website & CMS</h3><p class="muted">Club mini-site content and pages.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.branding.edit') }}"><h3>Branding</h3><p class="muted">Logo, color and presentation.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.domains.index') }}"><h3>Domains</h3><p class="muted">Hosted and custom addresses.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.site-settings.edit') }}"><h3>Site settings</h3><p class="muted">Community site configuration.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.navigation.index') }}"><h3>Navigation</h3><p class="muted">Control visitor journeys.</p></a><a class="pg-card pg-card-interactive" href="{{ route('tenant.media.index') }}"><h3>Media</h3><p class="muted">Reusable site assets.</p></a></div></section>
</div></section>
@endsection
