@extends('layouts.app')
@section('title','Manage '.$tenant->name)
@section('content')
@php($primary=$tenant->domains->firstWhere('is_primary',true))
@php($siteUrl=$primary?\App\Support\TenantUrl::to($primary):\App\Support\MountUrl::to('/'))
@php($isHosted=\App\Support\Edition::isHosted())
<section class="container section">
<div class="panel-head"><div><div class="eyebrow">{{$isHosted?'ORGANIZER CONTROL CENTER':'SELF-HOSTED CONTROL CENTER'}}</div><h1>{{$tenant->name}}</h1><p class="muted">{{$isHosted?'Manage your lifestyle website, membership applications, events, branding, domains and staff from one place.':'Manage this installation’s private website, events, members, branding and staff from one place.'}}</p>@if($siteUrl)<p class="muted">{{$isHosted?'Public address':'Site address'}}: <a class="text-link" target="_blank" rel="noopener" href="{{$siteUrl}}">{{$siteUrl}}</a></p>@endif</div><div class="row-actions">@if($siteUrl)<a class="btn primary" target="_blank" rel="noopener" href="{{$siteUrl}}">{{$isHosted?'Open Public Website':'Open Site'}}</a>@endif @if($isHosted)<a class="btn" target="_blank" rel="noopener" href="{{route('organizations.index',['preview'=>$tenant->id])}}">Preview Website</a><a class="btn" href="{{route('organizations.index')}}">My Sites</a>@endif</div></div>
<div class="stats"><div class="stat"><strong>{{$tenant->events_count}}</strong><span>Events</span></div><div class="stat"><strong>{{$tenant->domains->count()}}</strong><span>Domains</span></div><div class="stat"><strong>{{$isHosted?ucfirst($tenant->subscription?->plan?->name?:$tenant->plan):'Self-Hosted'}}</strong><span>{{$isHosted?'Plan':'Edition'}}</span></div></div>
<div class="dashboard-grid"><a class="panel action" href="{{route('tenant.events.index')}}">Manage Events</a>@if($isHosted)<a class="panel action" href="{{route('tenant.membership-applications.index')}}">Membership Applications</a>@else<a class="panel action" href="{{route('tenant.members.index')}}">Members & Approvals</a>@endif<a class="panel action" href="{{route('tenant.cms.pages')}}">Website & CMS</a><a class="panel action" href="{{route('tenant.domains.index')}}">Domains</a><a class="panel action" href="{{route('tenant.branding.edit')}}">Branding</a><a class="panel action" href="{{route('tenant.site-settings.edit')}}">Site Settings</a><a class="panel action" href="{{route('tenant.navigation.index')}}">Navigation</a><a class="panel action" href="{{route('tenant.media.index')}}">Media</a><a class="panel action" href="{{route('tenant.orders.index')}}">Orders</a><a class="panel action" href="{{route('tenant.analytics.index')}}">Analytics</a><a class="panel action" href="{{route('tenant.staff.index')}}">Staff</a></div>
</section>
@endsection
