@extends('layouts.app')
@section('title','Growth & Commerce · '.$tenant->name)
@section('content')
<section class="container section">
<div class="panel-head"><div><div class="eyebrow">GROWTH & COMMERCE</div><h1>{{$tenant->name}}</h1><p class="muted">Manage membership levels, event add-ons, promoters and consent-based marketing tools.</p></div><div class="row-actions"><a class="btn" href="{{route('tenant.growth.members.index')}}">Member Memberships</a><a class="btn" href="{{route('tenant.dashboard')}}">Control Center</a></div></div>
@if(session('status'))<div class="notice">{{session('status')}}</div>@endif
@if($errors->any())<div class="notice danger"><strong>Check the highlighted fields.</strong><ul>@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif

<div class="dashboard-grid">
<div class="panel"><h2>Membership levels</h2><form class="form-stack" method="post" action="{{route('tenant.growth.memberships.store')}}">@csrf
<input name="name" required maxlength="120" placeholder="Membership name"><input name="code" maxlength="80" placeholder="Code (optional)"><textarea name="description" rows="2" placeholder="Description"></textarea>
<div class="form-inline"><input name="price" type="number" step="0.01" min="0" value="0" required placeholder="Price"><input name="currency" value="USD" maxlength="3" required><select name="billing_interval"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual" selected>Annual</option><option value="lifetime">Lifetime</option></select></div>
<div class="form-inline"><input name="ticket_discount_percent" type="number" min="0" max="100" value="0" required><input name="sort_order" type="number" min="0" value="10" required></div>
<textarea name="benefits" rows="3" placeholder="Benefits, one per line"></textarea><label><input type="checkbox" name="application_required" value="1" checked> Application required</label><label><input type="checkbox" name="active" value="1" checked> Active</label><button class="btn primary">Create membership level</button></form>
@foreach($membershipLevels as $level)<div class="list-row"><div><strong>{{$level->name}}</strong><small>{{$level->code}} · {{number_format($level->price_cents/100,2)}} {{$level->currency}} · {{$level->billing_interval}}</small></div><span class="badge">{{$level->active?'Active':'Inactive'}}</span></div>@endforeach</div>

<div class="panel"><h2>Event add-ons</h2>
@if($events->isEmpty())<p class="muted">Create an event before adding paid extras.</p>@else
@foreach($events as $event)<details><summary><strong>{{$event->title}}</strong> <span class="muted">· {{$event->starts_at?->format('M j, Y')}}</span></summary><form class="form-stack" method="post" action="{{route('tenant.growth.addons.store',$event)}}">@csrf
<input name="name" required maxlength="160" placeholder="Add-on name"><textarea name="description" rows="2" placeholder="Description"></textarea><div class="form-inline"><select name="type"><option value="food">Food</option><option value="drink">Drink</option><option value="parking">Parking</option><option value="vip">VIP</option><option value="merchandise">Merchandise</option><option value="other" selected>Other</option></select><input name="price" type="number" step="0.01" min="0" value="0" required><input name="currency" value="USD" maxlength="3" required></div><div class="form-inline"><input name="quantity" type="number" min="0" placeholder="Inventory (blank = unlimited)"><input name="max_per_order" type="number" min="1" value="10" required><input name="sort_order" type="number" min="0" value="10" required></div><label><input type="checkbox" name="member_only" value="1"> Members only</label><label><input type="checkbox" name="active" value="1" checked> Active</label><button class="btn primary">Add event extra</button></form></details>@endforeach
@endif
@foreach($addons as $addon)<div class="list-row"><div><strong>{{$addon->name}}</strong><small>{{$addon->event_title}} · {{number_format($addon->price_cents/100,2)}} {{$addon->currency}}</small></div><form method="post" action="{{route('tenant.growth.addons.destroy',[$addon->event_id,$addon->id])}}">@csrf @method('DELETE')<button class="btn">Remove</button></form></div>@endforeach</div>

<div class="panel"><h2>Promoters</h2><form class="form-stack" method="post" action="{{route('tenant.growth.promoters.store')}}">@csrf<input name="name" required maxlength="160" placeholder="Promoter name"><input name="email" type="email" placeholder="Email"><input name="code" maxlength="80" placeholder="Tracking code"><div class="form-inline"><select name="status"><option value="active">Active</option><option value="paused">Paused</option><option value="disabled">Disabled</option></select><select name="commission_type"><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select><input name="commission_value" type="number" min="0" value="0" required></div><button class="btn primary">Add promoter</button></form>
@foreach($promoters as $promoter)<div class="list-row"><div><strong>{{$promoter->name}}</strong><small>{{$promoter->code}} · {{$promoter->commission_type}} {{$promoter->commission_value}}</small></div><span class="badge">{{$promoter->status}}</span></div>@endforeach</div>

<div class="panel"><h2>Consent-based contacts</h2><form class="form-stack" method="post" action="{{route('tenant.growth.contacts.store')}}">@csrf<div class="form-inline"><input name="first_name" maxlength="100" placeholder="First name"><input name="last_name" maxlength="100" placeholder="Last name"></div><input name="email" type="email" placeholder="Email"><input name="phone" maxlength="40" placeholder="Phone"><label><input type="checkbox" name="email_opt_in" value="1"> Record explicit email opt-in</label><label><input type="checkbox" name="sms_opt_in" value="1"> Record explicit SMS opt-in</label><p class="muted">Only mark an opt-in when the contact has actually consented to that channel.</p><button class="btn primary">Add contact</button></form>
@foreach($contacts as $contact)<div class="list-row"><div><strong>{{trim(($contact->first_name??'').' '.($contact->last_name??'')) ?: ($contact->email ?: $contact->phone)}}</strong><small>{{$contact->email}} {{$contact->phone}}</small></div><small>Email {{$contact->email_opt_in?'opted in':'no opt-in'}} · SMS {{$contact->sms_opt_in?'opted in':'no opt-in'}}</small></div>@endforeach</div>

<div class="panel"><h2>Marketing lists</h2><form class="form-stack" method="post" action="{{route('tenant.growth.lists.store')}}">@csrf<input name="name" required maxlength="160" placeholder="List name"><textarea name="description" rows="2" placeholder="Description"></textarea><button class="btn primary">Create list</button></form>@foreach($lists as $list)<div class="list-row"><strong>{{$list->name}}</strong></div>@endforeach</div>

<div class="panel"><h2>Campaign drafts</h2><form class="form-stack" method="post" action="{{route('tenant.growth.campaigns.store')}}">@csrf<input name="name" required maxlength="160" placeholder="Campaign name"><select name="marketing_list_id"><option value="">No list selected</option>@foreach($lists as $list)<option value="{{$list->id}}">{{$list->name}}</option>@endforeach</select><select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select><input name="subject" maxlength="255" placeholder="Email subject"><textarea name="body" rows="5" required placeholder="Campaign message"></textarea><div class="form-inline"><select name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select><input name="scheduled_at" type="datetime-local"></div><button class="btn primary">Save campaign</button></form><p class="muted">Saving a campaign does not bypass consent rules or immediately send it; delivery is handled by the campaign worker.</p>@foreach($campaigns as $campaign)<div class="list-row"><div><strong>{{$campaign->name}}</strong><small>{{$campaign->channel}} · {{$campaign->status}}</small></div></div>@endforeach</div>
</div>
</section>
@endsection
