@extends('layouts.app')
@section('title',$page->exists?'Edit '.$page->title:'New Page')
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">CLUB OS · WEBSITE BUILDER</span><h1>{{$page->exists?'Compose '.$page->title:'Create a new page'}}</h1><p>{{$page->exists?'Build the page section by section. Reorder with accessible controls, edit content in place, and preview without touching code.':'Start with a title and clean URL. You can add visual sections immediately after creation.'}}</p>@if($page->exists)<div class="pg-actions"><a class="button button-ghost" target="_blank" rel="noopener" href="{{ $page->is_homepage ? \App\Support\MountUrl::to('/') : route('site.page',$page->slug) }}">Preview page</a><a class="button button-ghost" href="{{route('tenant.builder.index')}}">Layouts</a><a class="button button-ghost" href="{{route('tenant.media.index')}}">Media library</a></div>@endif</div></section>
<section class="pg-page"><div class="pg-shell">
@if(session('status'))<div class="success" role="status">{{session('status')}}</div>@endif
@if($errors->any())<div class="error" role="alert">{{$errors->first()}}</div>@endif

@if(!$page->exists)
<form method="post" class="pg-card form-stack" action="{{route('tenant.cms.store')}}">@csrf<span class="pg-eyebrow">PAGE IDENTITY</span><h2>Name the page</h2><div class="form-grid"><label>Page title<input name="title" required maxlength="150" value="{{old('title')}}"></label><label>URL slug<input name="slug" maxlength="150" value="{{old('slug')}}" placeholder="about-us"></label></div><button class="button button-primary">Create page</button></form>
@else
<div class="pc-two" style="align-items:start">
<main>
<form method="post" class="pg-card form-stack" action="{{route('tenant.cms.update',$page)}}">@csrf @method('put')<div class="panel-head"><div><span class="pg-eyebrow">PAGE SETTINGS</span><h2>Publishing & search</h2></div><span class="pg-pill">{{$page->is_homepage?'Homepage':ucfirst($page->status)}}</span></div><div class="form-grid"><label>Title<input name="title" value="{{old('title',$page->title)}}" required maxlength="150"></label><label>Slug<input name="slug" value="{{old('slug',$page->slug)}}" required maxlength="150"></label><label>SEO title<input name="seo_title" value="{{old('seo_title',$page->seo_title)}}" maxlength="190"></label><label>Status<select name="status"><option value="draft" @selected(old('status',$page->status)==='draft')>Draft</option><option value="published" @selected(old('status',$page->status)==='published')>Published</option></select></label><label class="span2">SEO description<textarea name="seo_description" rows="3" maxlength="500">{{old('seo_description',$page->seo_description)}}</textarea></label></div><button class="button button-primary">Save page settings</button></form>

<section class="pg-section" aria-labelledby="sections-heading"><div class="pg-section-head"><div><span class="pg-eyebrow">PAGE FLOW</span><h2 id="sections-heading">{{$sections->count()}} section{{$sections->count()===1?'':'s'}}</h2><p>Top-to-bottom order matches the published page.</p></div></div>
<div class="pg-grid" data-builder-sections>
@forelse($sections as $index=>$section)
<article class="pg-card builder-block" id="section-{{$section->id}}">
<div class="panel-head"><div><span class="pg-pill">{{str_pad($index+1,2,'0',STR_PAD_LEFT)}} · {{str_replace('_',' ',$section->type)}}</span><h3>{{$section->name}}</h3></div><div class="pg-actions" aria-label="Reorder {{$section->name}}"><form method="post" action="{{route('tenant.cms.sections.move',[$section,'up'])}}">@csrf<button class="button button-ghost" aria-label="Move {{$section->name}} up" @disabled($loop->first)>↑ Up</button></form><form method="post" action="{{route('tenant.cms.sections.move',[$section,'down'])}}">@csrf<button class="button button-ghost" aria-label="Move {{$section->name}} down" @disabled($loop->last)>↓ Down</button></form></div></div>
<div class="pg-card" style="background:rgba(255,255,255,.025);margin-bottom:16px"><span class="pg-eyebrow">LIVE SUMMARY</span><h4 style="margin:.35rem 0">{{$section->content['heading']??$section->name}}</h4>@if(!empty($section->content['body']))<p class="muted">{{\Illuminate\Support\Str::limit($section->content['body'],180)}}</p>@endif @if(!empty($section->content['image_url']))<small>Image: {{$section->content['image_url']}}</small>@endif</div>
<form method="post" action="{{route('tenant.cms.sections.update',$section)}}" class="form-stack">@csrf @method('put')<div class="form-grid"><label>Section name<input name="name" value="{{$section->name}}" maxlength="120"></label><label>Heading<input name="heading" value="{{$section->content['heading']??''}}" maxlength="255"></label><label class="span2">Body<textarea name="body" rows="5" maxlength="10000">{{$section->content['body']??''}}</textarea></label><label>Image URL / media path<input name="image_url" value="{{$section->content['image_url']??''}}" maxlength="1000"></label><label>Image alt text<input name="image_alt" value="{{$section->content['image_alt']??''}}" maxlength="255"></label><label>Button label<input name="button_label" value="{{$section->content['button_label']??''}}" maxlength="80"></label><label>Button URL<input name="button_url" value="{{$section->content['button_url']??''}}" maxlength="500"></label><label>Fine sort order<input name="sort_order" type="number" min="0" max="100000" value="{{$section->sort_order}}"></label><label class="row-actions"><input type="checkbox" name="enabled" value="1" @checked($section->is_enabled)> Show this section</label></div><div class="pg-actions"><button class="button button-primary">Save section</button></div></form>
<form method="post" action="{{route('tenant.cms.sections.destroy',$section)}}" style="margin-top:10px">@csrf @method('delete')<button class="button button-ghost danger" data-confirm="Delete this section from the page?">Delete section</button></form>
</article>
@empty<div class="pg-empty"><h3>This page is an empty canvas.</h3><p>Add a hero, story, event grid or another section from the palette.</p></div>@endforelse
</div></section>
</main>

<aside class="pg-grid" style="position:sticky;top:120px"><section class="pg-card"><span class="pg-eyebrow">SECTION PALETTE</span><h2>Add content</h2><form method="post" action="{{route('tenant.cms.sections.store',$page)}}" class="form-stack">@csrf<label>Section type<select name="type">@foreach(['hero'=>'Hero','rich_text'=>'Rich text','image_text'=>'Image + text','event_grid'=>'Event grid','gallery'=>'Gallery','cta'=>'Call to action','faq'=>'FAQ','stats'=>'Stats','contact'=>'Contact','spacer'=>'Spacer'] as $value=>$label)<option value="{{$value}}">{{$label}}</option>@endforeach</select></label><label>Optional section name<input name="name" maxlength="120" placeholder="Membership story"></label><button class="button button-primary">Add section</button></form></section><section class="pg-card"><span class="pg-eyebrow">ACCESSIBLE ORDERING</span><h2>No drag-and-drop required.</h2><p class="muted">Up/Down buttons provide the same ordering control with a keyboard, screen reader or touch device. Fine sort order remains available for advanced adjustments.</p></section><section class="pg-card"><span class="pg-eyebrow">NEXT STEPS</span><div class="pg-grid"><a class="button button-ghost" href="{{route('tenant.navigation.index')}}">Navigation</a><a class="button button-ghost" href="{{route('tenant.branding.edit')}}">Branding & theme</a><a class="button button-ghost" href="{{route('tenant.media.index')}}">Media library</a></div></section></aside>
</div>
@endif
</div></section>
@endsection
