<?php

namespace App\Http\Controllers\Tenant;

use App\Models\CmsPage;
use App\Models\CmsSection;
use App\Support\Audit;
use App\Tenancy\TenantContext;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CmsController
{
    public function pages(TenantContext $c){$t=$c->requireTenant();return view('tenant.manage.cms.pages',['tenant'=>$t,'pages'=>$t->pages()->orderByDesc('is_homepage')->orderBy('title')->get()]);}
    public function create(){return view('tenant.manage.cms.edit',['page'=>new CmsPage,'sections'=>collect()]);}
    public function store(Request $r,TenantContext $c){$d=$r->validate(['title'=>'required|string|max:150','slug'=>'nullable|string|max:150']);$slug=Str::slug($d['slug']?:$d['title']);abort_if($c->requireTenant()->pages()->where('slug',$slug)->exists(),422,'That page slug is already used.');$p=$c->requireTenant()->pages()->create(['title'=>$d['title'],'slug'=>$slug,'status'=>'draft','is_homepage'=>false]);return redirect()->route('tenant.cms.edit',$p)->with('status','Page created.');}
    public function edit(TenantContext $c,CmsPage $page){abort_unless($page->tenant_id===$c->id(),404);return view('tenant.manage.cms.edit',['page'=>$page,'sections'=>$page->sections()->orderBy('sort_order')->orderBy('id')->get()]);}
    public function update(Request $r,TenantContext $c,CmsPage $page){abort_unless($page->tenant_id===$c->id(),404);$d=$r->validate(['title'=>'required|string|max:150','slug'=>'required|string|max:150','seo_title'=>'nullable|string|max:190','seo_description'=>'nullable|string|max:500','status'=>'required|in:draft,published']);$slug=Str::slug($d['slug']);abort_if(CmsPage::where('tenant_id',$c->id())->where('slug',$slug)->whereKeyNot($page->id)->exists(),422,'That page slug is already used.');$before=$page->toArray();$page->update($d+['slug'=>$slug,'published_at'=>$d['status']==='published'?($page->published_at??now()):null]);Audit::write('cms.page.updated',$page,$before,$page->fresh()->toArray(),$c->id(),$r);return back()->with('status','Page saved.');}
    public function addSection(Request $r,TenantContext $c,CmsPage $page){abort_unless($page->tenant_id===$c->id(),404);$d=$r->validate(['type'=>'required|in:hero,rich_text,image_text,event_grid,gallery,cta,faq,stats,contact,spacer','name'=>'nullable|string|max:120']);$page->sections()->create(['type'=>$d['type'],'name'=>$d['name']?:ucwords(str_replace('_',' ',$d['type'])),'content'=>self::defaults($d['type']),'settings'=>[],'sort_order'=>(int)$page->sections()->max('sort_order')+10,'is_enabled'=>true]);return back()->with('status','Section added.');}
    public function updateSection(Request $r,TenantContext $c,CmsSection $section){$section->load('page');abort_unless($section->page?->tenant_id===$c->id(),404);$d=$r->validate(['name'=>'nullable|string|max:120','heading'=>'nullable|string|max:255','body'=>'nullable|string|max:10000','button_label'=>'nullable|string|max:80','button_url'=>'nullable|string|max:500','image_url'=>'nullable|string|max:1000','image_alt'=>'nullable|string|max:255','sort_order'=>'nullable|integer|min:0|max:100000']);$before=$section->toArray();$section->update(['name'=>$d['name']?:$section->name,'content'=>array_merge($section->content??[],array_filter(['heading'=>$d['heading']??null,'body'=>$d['body']??null,'button_label'=>$d['button_label']??null,'button_url'=>$d['button_url']??null,'image_url'=>$d['image_url']??null,'image_alt'=>$d['image_alt']??null],fn($v)=>$v!==null)),'sort_order'=>$d['sort_order']??$section->sort_order,'is_enabled'=>$r->boolean('enabled')]);Audit::write('cms.section.updated',$section,$before,$section->fresh()->toArray(),$c->id(),$r);return back()->with('status','Section updated.');}
    public function moveSection(Request $r,TenantContext $c,CmsSection $section,string $direction){$section->load('page');abort_unless($section->page?->tenant_id===$c->id(),404);abort_unless(in_array($direction,['up','down'],true),404);DB::transaction(function()use($section,$direction){$locked=CmsSection::whereKey($section->id)->lockForUpdate()->firstOrFail();$query=CmsSection::where('cms_page_id',$locked->cms_page_id)->whereKeyNot($locked->id);$other=$direction==='up'?$query->where('sort_order','<=',$locked->sort_order)->orderByDesc('sort_order')->orderByDesc('id')->lockForUpdate()->first():$query->where('sort_order','>=',$locked->sort_order)->orderBy('sort_order')->orderBy('id')->lockForUpdate()->first();if(!$other)return;$a=(int)$locked->sort_order;$b=(int)$other->sort_order;if($a===$b){$locked->update(['sort_order'=>$direction==='up'?$a-1:$a+1]);}else{$locked->update(['sort_order'=>$b]);$other->update(['sort_order'=>$a]);}});return back()->with('status','Section moved '.($direction==='up'?'up.':'down.'));}
    public function deleteSection(TenantContext $c,CmsSection $section){$section->load('page');abort_unless($section->page?->tenant_id===$c->id(),404);$section->delete();return back()->with('status','Section removed.');}
    private static function defaults(string $type):array{return match($type){'hero'=>['heading'=>'New hero','body'=>'Edit this section from the website builder.','button_label'=>'Learn more','button_url'=>'/events'],'event_grid'=>['heading'=>'Upcoming Events','limit'=>6],'cta'=>['heading'=>'Join us','body'=>'Create an account and discover upcoming events.','button_label'=>'Join','button_url'=>'/register'],'gallery'=>['heading'=>'Gallery','body'=>'Add visual highlights from your media library.'],'faq'=>['heading'=>'Frequently asked questions','body'=>'Add the answers visitors need before they join.'],'stats'=>['heading'=>'Community at a glance','body'=>'Highlight meaningful community numbers.'],'contact'=>['heading'=>'Get in touch','body'=>'Tell prospective members how to reach your team.'],default=>['heading'=>ucwords(str_replace('_',' ',$type)),'body'=>'Add your content here.']};}
}
