<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('ticket_types',function(Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->unsignedInteger('price_cents')->default(0);$t->string('currency',3)->default('USD');$t->unsignedInteger('quantity')->nullable();$t->unsignedInteger('max_per_order')->default(10);$t->timestamp('sales_start_at')->nullable();$t->timestamp('sales_end_at')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('promo_codes',function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('event_id')->nullable()->constrained()->cascadeOnDelete();$t->string('code');$t->string('discount_type')->default('percent');$t->unsignedInteger('discount_value');$t->unsignedInteger('max_uses')->nullable();$t->unsignedInteger('uses')->default(0);$t->timestamp('expires_at')->nullable();$t->boolean('active')->default(true);$t->timestamps();$t->unique(['tenant_id','code']);});
  Schema::create('orders',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('status')->default('pending')->index();$t->string('currency',3)->default('USD');$t->unsignedInteger('subtotal_cents')->default(0);$t->unsignedInteger('discount_cents')->default(0);$t->unsignedInteger('fee_cents')->default(0);$t->unsignedInteger('total_cents')->default(0);$t->string('promo_code')->nullable();$t->timestamps();});
  Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('ticket_type_id')->constrained()->restrictOnDelete();$t->unsignedInteger('quantity');$t->unsignedInteger('unit_price_cents');$t->unsignedInteger('total_cents');$t->timestamps();});
  Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('provider');$t->string('provider_reference')->nullable()->index();$t->string('status')->default('pending')->index();$t->unsignedInteger('amount_cents');$t->string('currency',3)->default('USD');$t->json('metadata')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
  Schema::create('tickets',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('order_item_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('qr_token',80)->unique();$t->string('status')->default('valid')->index();$t->timestamp('checked_in_at')->nullable();$t->timestamps();});
 }
 public function down():void{Schema::dropIfExists('tickets');Schema::dropIfExists('payments');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('promo_codes');Schema::dropIfExists('ticket_types');}
};
