<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('event_checkins',function(Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('ticket_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('checked_in_by')->nullable()->constrained('users')->nullOnDelete();$t->string('method')->default('manual');$t->unsignedSmallInteger('guest_count')->default(1);$t->timestamp('checked_in_at');$t->json('metadata')->nullable();$t->timestamps();$t->index(['event_id','checked_in_at']);});
  Schema::create('reports',function(Blueprint $t){$t->id();$t->foreignId('reporter_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('tenant_id')->nullable()->constrained()->cascadeOnDelete();$t->string('reportable_type');$t->unsignedBigInteger('reportable_id');$t->string('category')->index();$t->text('details')->nullable();$t->string('status')->default('open')->index();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['reportable_type','reportable_id']);});
  Schema::create('moderation_actions',function(Blueprint $t){$t->id();$t->foreignId('report_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('target_type');$t->unsignedBigInteger('target_id');$t->string('action');$t->text('reason')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['target_type','target_id']);});
  Schema::create('verifications',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('tenant_id')->nullable()->constrained()->cascadeOnDelete();$t->string('type')->index();$t->string('status')->default('pending')->index();$t->string('provider')->nullable();$t->string('provider_reference')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('verified_at')->nullable();$t->timestamp('expires_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
 }
 public function down():void{Schema::dropIfExists('verifications');Schema::dropIfExists('moderation_actions');Schema::dropIfExists('reports');Schema::dropIfExists('event_checkins');}
};