<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('plans',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->unsignedInteger('price_monthly_cents')->default(0);$t->string('currency',3)->default('USD');$t->json('features')->nullable();$t->boolean('active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
  Schema::create('tenant_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->unique()->constrained()->cascadeOnDelete();$t->foreignId('plan_id')->nullable()->constrained()->nullOnDelete();$t->string('status')->default('active')->index();$t->string('provider')->nullable();$t->string('provider_reference')->nullable();$t->timestamp('trial_ends_at')->nullable();$t->timestamp('current_period_ends_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('email_templates',function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->constrained()->cascadeOnDelete();$t->string('key');$t->string('name');$t->string('subject');$t->longText('body_html');$t->longText('body_text')->nullable();$t->boolean('enabled')->default(true);$t->timestamps();$t->unique(['tenant_id','key']);});
  Schema::create('analytics_events',function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('event_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('event_name')->index();$t->string('session_key',80)->nullable()->index();$t->string('path',500)->nullable();$t->string('referrer',1000)->nullable();$t->json('properties')->nullable();$t->timestamp('occurred_at')->index();$t->timestamps();$t->index(['tenant_id','event_name','occurred_at']);});
 }
 public function down():void{Schema::dropIfExists('analytics_events');Schema::dropIfExists('email_templates');Schema::dropIfExists('tenant_subscriptions');Schema::dropIfExists('plans');}
};