@extends('layouts.app')
@section('title','Member Client Area')
@section('content')
<section class="shell section pg-suite-shell pg-client-area">
    <div class="pg-suite-pagehead"><div><span class="eyebrow">MEMBER CLIENT AREA</span><h1>Welcome, {{ $user->display_name ?: $user->name }}</h1><p>{{ $tenant ? 'Your '.$tenant->name.' community, profile, galleries, messages and events are all here.' : 'Manage your Private Gather profile and every club community you belong to.' }}</p></div><div class="row-actions">@if($tenant)<a class="button button-primary" href="{{ route('community.index') }}">Enter Community</a>@endif<a class="button button-ghost" href="{{ route('profile.edit') }}">Profile & Privacy</a></div></div>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif

    @php($trustBadge=app(\App\Services\Verification\MemberTrust::class)->badge($user))
    <section class="panel pg-member-trust-summary"><div class="panel-head"><div><span class="eyebrow">IDENTITY & AGE VERIFICATION</span><h2>{{$trustBadge['label']}}</h2></div><span class="status-pill {{$trustBadge['verified']?'status-ok':'status-pending'}}">{{$trustBadge['verified']?'Verified':'Action available'}}</span></div><p class="muted">{{$trustBadge['verified']?'Your high-assurance verification is current.':'Verification is required before an existing member profile can join an additional club. Couple profiles require both linked partners.'}}</p><a class="button button-ghost" href="{{route('verification.index')}}">Manage Verification</a></section>

    @if(!$tenant)
    <section class="panel pg-club-switcher"><div class="panel-head"><div><span class="eyebrow">MY CLUBS</span><h2>Your communities</h2></div><span class="muted">{{ $user->tenants->count() }}</span></div><div class="pg-club-grid">@forelse($user->tenants as $club) @php($domain=$club->primaryDomain?->domain)<article><strong>{{ $club->name }}</strong><small>{{ ucfirst($club->pivot->status) }} · {{ ucfirst($club->pivot->role) }}</small>@if($domain)<a class="button button-ghost" href="https://{{ $domain }}/dashboard">Open Club</a>@endif</article>@empty<p class="muted">You have not joined a club yet. Browse communities and apply from the club site.</p>@endforelse</div></section>
    @endif

    <div class="pg-client-stats"><a href="{{ $tenant?route('network.index').'#connections':route('site.organizations') }}"><strong>{{ $connectionCount }}</strong><span>Connections</span></a><a href="{{ $tenant?route('network.index').'#groups':route('site.organizations') }}"><strong>{{ $groupCount }}</strong><span>Groups</span></a><a href="{{ $tenant?route('network.index').'#galleries':route('profile.edit') }}"><strong>{{ $albums->count() }}</strong><span>Galleries</span></a><a href="{{ route('notifications.index') }}"><strong>{{ $unreadNotifications }}</strong><span>Unread Alerts</span></a></div>

    @if($applications->isNotEmpty())<section class="panel"><div class="panel-head"><div><span class="eyebrow">MEMBERSHIP</span><h2>Applications & access</h2></div></div><div class="pg-status-list">@foreach($applications as $application)<article><div><strong>{{ $application->tenant?->name }}</strong><small>Submitted {{ $application->created_at->diffForHumans() }}</small></div><span class="status-pill {{ $application->status==='approved'?'status-ok':'status-pending' }}">{{ ucfirst($application->status) }}</span></article>@endforeach</div></section>@endif

    <div class="pg-client-grid">
        <section class="panel"><div class="panel-head"><div><span class="eyebrow">MESSAGES</span><h2>Recent conversations</h2></div><a href="{{ route('messages.index') }}">All messages →</a></div>@forelse($conversations as $conversation) @php($other=$conversation->participants->firstWhere('id','!=',$user->id)) @php($last=$conversation->messages->first())@php($conversationUrl=$tenant?route('messages.show',$conversation):($conversation->tenant?->primaryDomain?->domain?'https://'.$conversation->tenant->primaryDomain->domain.'/messages/'.$conversation->id:'#'))<a class="pg-dashboard-row" href="{{ $conversationUrl }}"><div><strong>{{ $conversation->subject ?: ($other?->display_name ?: $other?->name ?: 'Conversation') }}</strong><small>{{ $last?->body?\Illuminate\Support\Str::limit($last->body,60):($last?->attachment_path?'Media attachment':'No messages yet') }}</small></div><span>›</span></a>@empty<p class="muted">No private conversations yet.</p>@endforelse</section>

        <section class="panel"><div class="panel-head"><div><span class="eyebrow">NOTIFICATIONS</span><h2>Recent activity</h2></div><a href="{{ route('notifications.index') }}">All alerts →</a></div>@forelse($notifications as $notification) @php($data=$notification->data??[])<a class="pg-dashboard-row {{ $notification->read_at?'':'is-unread' }}" href="{{ $data['url']??route('notifications.index') }}"><div><strong>{{ $data['title']??ucfirst($notification->type) }}</strong><small>{{ $notification->created_at->diffForHumans() }}</small></div><span>›</span></a>@empty<p class="muted">No notifications yet.</p>@endforelse</section>

        <section class="panel"><div class="panel-head"><div><span class="eyebrow">EVENTS</span><h2>Your RSVPs</h2></div><a href="{{ route('site.events') }}">Discover events →</a></div>@forelse($rsvps as $rsvp)<a class="pg-dashboard-row" href="{{ route('events.show',$rsvp->event) }}"><div><strong>{{ $rsvp->event?->title }}</strong><small>{{ $rsvp->event?->starts_at?->format('M j, Y · g:i A') }}</small></div><span class="status-pill">{{ ucfirst($rsvp->status) }}</span></a>@empty<p class="muted">No RSVPs yet.</p>@endforelse</section>

        <section class="panel"><div class="panel-head"><div><span class="eyebrow">YOUR CONTENT</span><h2>Wall & galleries</h2></div>@if($tenant)<a href="{{ route('members.show',$user) }}">My wall →</a>@endif</div><div class="pg-content-totals"><div><strong>{{ $posts->count() }}</strong><span>Recent wall posts</span></div><div><strong>{{ $albums->sum('photos_count') }}</strong><span>Gallery items</span></div></div>@if($tenant)<div class="row-actions"><a class="button button-ghost" href="{{ route('members.show',$user) }}">Open My Wall</a><a class="button button-ghost" href="{{ route('network.index') }}#galleries">Manage Galleries</a><a class="button button-ghost" href="{{ route('rewards.index') }}">Membership Card & Rewards</a></div>@else<p class="muted">Open one of your club sites to post on its private wall and manage club-specific galleries.</p>@endif</section>
    </div>
</section>
@endsection
