@extends('layouts.app')
@section('title','My Membership · '.$tenant->name)
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">{{$tenant->name}} · MEMBERSHIP</span><h1>Your access, billing state and benefits in one place.</h1><p>Membership terms and recurring billing are shown separately so you can see exactly what grants access and what is scheduled to charge or cancel.</p></div></section>
<section class="pg-page"><div class="pg-shell pg-grid">
@if(session('status'))<div class="success" role="status">{{session('status')}}</div>@endif
<section class="pg-card">@if($term)<div class="panel-head"><div><span class="pg-eyebrow">CURRENT ACCESS</span><h2>{{$term->level->name}}</h2><p class="muted">{{$term->level->description}}</p></div><span class="pg-pill">{{ucfirst($term->status)}}</span></div><div class="pg-grid pg-grid-4"><div class="pg-stat"><span>Configured price</span><strong>{{$term->level->priceLabel()}}</strong></div><div class="pg-stat"><span>Term</span><strong style="font-size:1.35rem">{{ucfirst($term->level->billing_interval)}}</strong></div><div class="pg-stat"><span>Current end</span><strong style="font-size:1.35rem">{{$term->expires_at?->format('M j, Y')??'No expiration'}}</strong></div><div class="pg-stat"><span>Event discount</span><strong>{{$term->level->event_discount_percent}}%</strong></div></div>@if($term->cancel_at_period_end)<div class="pg-privacy-note">Access is scheduled to end at the current period boundary. No future renewal is expected from this membership term.</div>@endif @if($term->level->benefits)<div style="margin-top:18px"><h3>Included benefits</h3><ul>@foreach($term->level->benefits as $benefit)<li>{{$benefit}}</li>@endforeach</ul></div>@endif @elseif($hasMembership)<span class="pg-eyebrow">LEGACY ACCESS</span><h2>Your existing membership is preserved.</h2><p>This community has not yet mapped your active access to a structured level.</p>@else<span class="pg-eyebrow">MEMBERSHIP</span><h2>No active membership</h2><p>You do not currently have active member access to {{$tenant->name}}. Use the community’s application process or contact its membership team.</p>@endif</section>

<section class="pg-card"><div class="panel-head"><div><span class="pg-eyebrow">BILLING LIFECYCLE</span><h2>Recurring subscription</h2></div>@if($subscription)<span class="pg-pill">{{ucfirst(str_replace('_',' ',$subscription->status))}}</span>@endif</div>@if($subscription)<div class="pg-grid pg-grid-3"><div class="pg-stat"><span>Amount</span><strong>${{number_format($subscription->amount_cents/100,2)}}</strong></div><div class="pg-stat"><span>Billing</span><strong style="font-size:1.25rem">{{ucfirst($subscription->billing_interval)}}</strong></div><div class="pg-stat"><span>Period ends</span><strong style="font-size:1.25rem">{{$subscription->current_period_ends_at?\Carbon\Carbon::parse($subscription->current_period_ends_at)->format('M j, Y'):'Not scheduled'}}</strong></div></div><p class="muted">Provider: {{$subscription->provider}} @if($subscription->provider_reference) · Reference {{$subscription->provider_reference}} @endif</p>@if($subscription->cancel_at_period_end)<div class="pg-privacy-note">Cancellation is already scheduled for the end of this billing period.</div>@elseif(in_array($subscription->status,['active','pending_provider'],true))<form method="post" action="{{route('membership.subscription.cancel',$subscription->id)}}" style="margin-top:16px">@csrf @method('PATCH')<button class="button button-ghost" data-confirm="Schedule this membership subscription to cancel at the end of its current period?">Cancel at period end</button></form>@endif @else<div class="pg-empty"><h3>No recurring subscription record</h3><p>Free, lifetime, complimentary and legacy memberships may not need recurring billing.</p></div>@endif</section>

<section class="pg-card"><span class="pg-eyebrow">AVAILABLE LEVELS</span><h2>{{$tenant->name}} membership options</h2><div class="pg-grid pg-grid-2">@forelse($levels as $level)<article class="pg-card"><div class="row-between"><div><h3>{{$level->name}}</h3><p class="muted">{{$level->description}}</p></div>@if($level->is_default)<span class="pg-pill">Default</span>@endif</div><strong style="font-size:1.4rem">{{$level->priceLabel()}}</strong><small style="display:block">{{ucfirst($level->billing_interval)}} · {{$level->profile_eligibility==='any'?'Couples & individuals':ucfirst($level->profile_eligibility).' profiles'}}</small>@if($level->benefits)<ul>@foreach($level->benefits as $benefit)<li>{{$benefit}}</li>@endforeach</ul>@endif</article>@empty<div class="pg-empty">This community has not published structured membership levels yet.</div>@endforelse</div><p class="muted">Paid recurring activation depends on the community’s connected merchant provider. Private Gather does not mark external billing complete until the provider workflow confirms it.</p></section>
</div></section>
@endsection
