@extends('layouts.app')
@section('title','Lifestyle Profile & Privacy')
@section('content')
<section class="shell section pg-profile-editor"><div class="panel-head"><div><span class="eyebrow">MEMBER CLIENT AREA</span><h1>Lifestyle Profile & Privacy</h1><p class="muted">Control what other club members see. Sensitive lifestyle fields are never tied to your legal account name in member-facing pages.</p></div><a class="button button-ghost" href="{{route('dashboard')}}">Dashboard</a></div>
@if(session('status'))<div class="notice">{{session('status')}}</div>@endif
<div class="pg-profile-editor-grid">
<div>
<form method="post" class="panel form-stack">@csrf @method('put')
<h2>Profile identity</h2><div class="form-grid"><label>Username <small>Global across Private Gather</small><input name="username" value="{{old('username',auth()->user()->username ?: auth()->user()->display_name)}}" minlength="3" maxlength="32" pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,31}" required></label><label>Profile / member type<select name="lifestyle_identity" required>@foreach($lifestyleIdentities as $value=>$label)<option value="{{$value}}" @selected(old('lifestyle_identity',$profile?->lifestyle_identity?:($profile?->profile_type==='couple'?'couple':'individual'))===$value)>{{$label}}</option>@endforeach</select></label><label>Relationship status<select name="relationship_status"><option value="">Not specified</option>@foreach($relationshipStatuses as $value=>$label)<option value="{{$value}}" @selected(old('relationship_status',$profile?->relationship_status)===$value)>{{$label}}</option>@endforeach</select></label><label>Experience level<select name="experience_level"><option value="">Not specified</option>@foreach($experienceLevels as $value=>$label)<option value="{{$value}}" @selected(old('experience_level',$profile?->experience_level)===$value)>{{$label}}</option>@endforeach</select></label><label>Pronouns<input name="pronouns" value="{{old('pronouns',$profile?->pronouns)}}"></label><label>City<input name="city" value="{{old('city',$profile?->city)}}"></label><label>State<select name="region"><option value="">Not specified</option>@foreach($usStates as $value=>$label)<option value="{{$value}}" @selected(old('region',$profile?->region)===$value)>{{$label}}</option>@endforeach</select></label><label class="span2">Headline<input name="headline" value="{{old('headline',$profile?->headline)}}"></label><label class="span2">About us / me<textarea name="bio" rows="6">{{old('bio',$profile?->bio)}}</textarea></label><label class="span2">General interests <small>Comma-separated</small><input name="interests" value="{{old('interests',implode(', ',$profile?->interests??[]))}}"></label></div>

<h2>Connection preferences</h2><div class="pg-choice-grid">@foreach($lookingForOptions as $value=>$label)<label class="pg-choice"><input type="checkbox" name="looking_for[]" value="{{$value}}" @checked(in_array($value,(array)old('looking_for',$profile?->looking_for??[]),true))><span>{{$label}}</span></label>@endforeach</div>
<h2>Lifestyle interests</h2><div class="pg-choice-grid">@foreach($lifestyleInterestOptions as $value=>$label)<label class="pg-choice"><input type="checkbox" name="lifestyle_interests[]" value="{{$value}}" @checked(in_array($value,(array)old('lifestyle_interests',$profile?->lifestyle_interests??[]),true))><span>{{$label}}</span></label>@endforeach</div>
<label>Boundaries / comfort notes <small>Keep this factual and only share what you are comfortable revealing.</small><textarea name="boundaries" rows="5" maxlength="2500">{{old('boundaries',$profile?->boundaries)}}</textarea></label>

<h2>Privacy</h2>@php($visibility=$profile?->visibility??[])<div class="form-grid"><label>Who can view my profile?<select name="visibility_profile">@foreach($visibilityOptions as $value=>$label)<option value="{{$value}}" @selected(($visibility['profile']??'members')===$value)>{{$label}}</option>@endforeach</select></label><label>Location visibility<select name="visibility_location">@foreach($visibilityOptions as $value=>$label)<option value="{{$value}}" @selected(($visibility['location']??'members')===$value)>{{$label}}</option>@endforeach</select></label><label>Lifestyle preferences visibility<select name="visibility_lifestyle">@foreach($visibilityOptions as $value=>$label)<option value="{{$value}}" @selected(($visibility['lifestyle']??'members')===$value)>{{$label}}</option>@endforeach</select></label><label>Boundaries visibility<select name="visibility_boundaries">@foreach($visibilityOptions as $value=>$label)<option value="{{$value}}" @selected(($visibility['boundaries']??'connections')===$value)>{{$label}}</option>@endforeach</select></label><label>Gallery visibility default<select name="visibility_photos">@foreach($visibilityOptions as $value=>$label)<option value="{{$value}}" @selected(($visibility['photos']??'members')===$value)>{{$label}}</option>@endforeach</select></label><label>Who can message me?<select name="message_permissions"><option value="members" @selected(($profile?->message_permissions??'members')==='members')>Any active club member</option><option value="connections" @selected($profile?->message_permissions==='connections')>Connections only</option><option value="none" @selected($profile?->message_permissions==='none')>Nobody</option></select></label></div>
<label class="check"><input type="checkbox" name="discoverable" value="1" @checked($profile?->discoverable??true)> Allow my profile to appear in the club member directory.</label><label class="check"><input type="checkbox" name="show_age" value="1" @checked($profile?->show_age)> Show my age to members who can view my profile.</label><label class="check"><input type="checkbox" name="show_last_active" value="1" @checked($profile?->show_last_active??true)> Show when I was recently active.</label>
<button class="button button-primary">Save Profile & Privacy</button></form>
</div>
<aside class="pg-profile-tools">
<div class="panel"><h2>Profile photos</h2><p class="muted">Avatar and cover photos are kept behind club membership access.</p>@if($profile?->avatar_path)<img class="pg-profile-preview-avatar" src="{{route('profile.media.show','avatar')}}" alt="Current avatar">@endif<form method="post" action="{{route('profile.media')}}" enctype="multipart/form-data" class="form-stack">@csrf<input type="hidden" name="kind" value="avatar"><label>Avatar<input type="file" name="media" accept="image/jpeg,image/png,image/webp,image/gif" required></label><button class="btn">Upload Avatar</button></form>@if($profile?->cover_path)<img class="pg-profile-preview-cover" src="{{route('profile.media.show','cover')}}" alt="Current cover">@endif<form method="post" action="{{route('profile.media')}}" enctype="multipart/form-data" class="form-stack">@csrf<input type="hidden" name="kind" value="cover"><label>Cover photo<input type="file" name="media" accept="image/jpeg,image/png,image/webp,image/gif" required></label><button class="btn">Upload Cover</button></form></div>
@if($tenant)<div class="panel"><span class="eyebrow">COUPLE / PARTNER LINK</span><h3>Linked partner profile</h3>@if($profile?->partner)<p><strong>{{ $profile->partner->display_name ?: $profile->partner->name }}</strong></p><p class="muted">You each keep separate logins, messages, galleries and privacy controls while profiles can show the relationship.</p><form method="post" action="{{ route('profile.partner.unlink') }}">@csrf @method('DELETE')<button class="btn">Unlink Partner</button></form>@else<p class="muted">If you and your partner prefer separate accounts, send a mutual link request. Verified couple profiles require two separately authenticated, linked partner accounts so each person can complete verification independently.</p>@if($partnerCandidates->isNotEmpty())<form class="form-stack" method="post" action="{{ route('profile.partner.invite') }}">@csrf<label>Partner<select name="partner_user_id" required><option value="">Choose an active club member</option>@foreach($partnerCandidates as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->display_name ?: $candidate->name }}</option>@endforeach</select></label><button class="button button-ghost">Send Partner Link</button></form>@endif @endif @if($partnerInvites->isNotEmpty())<hr><strong>Pending requests</strong>@foreach($partnerInvites as $invite)<div class="pg-partner-invite"><span>{{ $invite->sender?->display_name ?: $invite->sender?->name }}</span><div class="row-actions"><form method="post" action="{{ route('profile.partner.respond',$invite) }}">@csrf<input type="hidden" name="decision" value="accept"><button class="btn primary">Accept</button></form><form method="post" action="{{ route('profile.partner.respond',$invite) }}">@csrf<input type="hidden" name="decision" value="decline"><button class="btn">Decline</button></form></div></div>@endforeach @endif</div>@endif
@php($trustBadge=app(\App\Services\Verification\MemberTrust::class)->badge(auth()->user()))
<div class="panel pg-verification-card"><span class="eyebrow">MEMBER VERIFICATION</span><h3>{{$trustBadge['label']}}</h3><p class="muted">High-assurance verification uses government ID plus a live selfie/liveness check. Couple profiles require both linked partners to pass independently.</p><a class="button button-ghost" href="{{route('verification.index')}}">{{$trustBadge['verified']?'View Verification':'Verify Member Identity'}}</a></div>
<div class="panel"><h3>Personal community spaces</h3><a class="button button-ghost" href="{{route('members.show',auth()->user())}}">My Wall & Gallery</a><a class="button button-ghost" href="{{route('network.index')}}#albums">My Albums</a><a class="button button-ghost" href="{{route('notifications.index')}}">Notifications</a></div>
</aside>
</div></section>
@endsection
