@extends('layouts.app')
@section('title',($member->display_name?:$member->name).' · '.$tenant->name)
@section('content')
@php($verificationBadge=app(\App\Services\Verification\MemberTrust::class)->badge($member))
@php
$mine=(int)$viewer->id===(int)$member->id;
$identityLabels=\App\Support\LifestyleProfileOptions::identities();
$relationshipLabels=\App\Support\LifestyleProfileOptions::relationshipStatuses();
$experienceLabels=\App\Support\LifestyleProfileOptions::experienceLevels();
$lookingLabels=\App\Support\LifestyleProfileOptions::lookingFor();
$interestLabels=\App\Support\LifestyleProfileOptions::interests();
@endphp
<section class="shell section pg-member-profile-page">
<div class="pg-member-cover panel">@if($profile?->cover_path)<img src="{{route('members.media',[$member,'cover'])}}" alt="">@endif<div class="pg-member-cover-gradient"></div><div class="pg-member-profile-head">@if($profile?->avatar_path)<img class="pg-member-avatar-img" src="{{route('members.media',[$member,'avatar'])}}" alt="{{ $member->display_name?:$member->name }}">@else<div class="pg-member-avatar-fallback">{{strtoupper(substr($member->display_name?:$member->name,0,2))}}</div>@endif<div><span class="eyebrow">{{ strtoupper($identityLabels[$profile?->lifestyle_identity]??'MEMBER') }}</span><h1>{{ $member->display_name?:$member->name }}</h1><p>{{ $profile?->headline }}</p><div class="pg-badge-row"><span class="pg-member-badge {{$verificationBadge['verified']?'pg-member-badge-verified':'pg-member-badge-unverified'}}">{{$verificationBadge['verified']?'✓':'○'}} {{$verificationBadge['label']}}</span>@foreach($badges as $badge)<span class="pg-member-badge">{{$badge->icon?:'◆'}} {{$badge->label}}</span>@endforeach</div></div></div></div>

<div class="pg-member-profile-grid"><main>
<div class="panel pg-profile-details"><div class="row-between"><h2>About</h2><div class="row-actions">@if($mine)<a class="button button-primary" href="{{route('profile.edit')}}">Edit Profile</a>@else @if($canMessage)<a class="button button-primary" href="{{route('messages.index',['recipient'=>$member->id])}}">Message</a>@endif @if(!$isConnected)<form method="post" action="{{route('network.connections.request',$member)}}">@csrf<button class="button button-ghost">Connect</button></form>@endif <form method="post" action="{{route('members.block',$member)}}">@csrf<button class="btn">Block</button></form><details class="pg-inline-report"><summary>Report</summary><form method="post" action="{{route('reports.store')}}" class="form-stack">@csrf<input type="hidden" name="reportable_type" value="user"><input type="hidden" name="reportable_id" value="{{$member->id}}"><label>Reason<select name="category"><option value="harassment">Harassment</option><option value="safety">Safety / consent</option><option value="privacy">Privacy</option><option value="spam">Spam</option><option value="fraud">Fraud</option><option value="inappropriate">Inappropriate content</option><option value="other">Other</option></select></label><label>Details<textarea name="details" rows="3"></textarea></label><button class="btn">Submit Report</button></form></details>@endif</div></div>
@if($profile?->bio)<div class="prose">{!!nl2br(e($profile->bio))!!}</div>@endif
<div class="pg-profile-facts">@if($privacy->fieldVisible($profile,'location',$tenant->id,$viewer->id,$member->id)&&($profile?->city||$profile?->region))<div><span>Location</span><strong>{{collect([$profile->city,$profile->region])->filter()->implode(', ')}}</strong></div>@endif @if($profile?->show_age&&$member->date_of_birth)<div><span>Age</span><strong>{{$member->date_of_birth->age}}</strong></div>@endif @if($profile?->pronouns)<div><span>Pronouns</span><strong>{{$profile->pronouns}}</strong></div>@endif @if($profile?->show_last_active&&$member->last_login_at)<div><span>Last active</span><strong>{{$member->last_login_at->diffForHumans()}}</strong></div>@endif</div>
@if($privacy->fieldVisible($profile,'lifestyle',$tenant->id,$viewer->id,$member->id))<div class="pg-lifestyle-details"><h3>Lifestyle</h3><div class="pg-profile-facts">@if($profile?->relationship_status)<div><span>Relationship</span><strong>{{$relationshipLabels[$profile->relationship_status]??ucwords(str_replace('_',' ',$profile->relationship_status))}}</strong></div>@endif @if($profile?->experience_level)<div><span>Experience</span><strong>{{$experienceLabels[$profile->experience_level]??ucwords(str_replace('_',' ',$profile->experience_level))}}</strong></div>@endif</div>@if($profile?->looking_for)<h4>Looking to connect with</h4><div class="pg-tag-cloud">@foreach($profile->looking_for as $tag)<span>{{$lookingLabels[$tag]??ucwords(str_replace('_',' ',$tag))}}</span>@endforeach</div>@endif @if($profile?->lifestyle_interests)<h4>Interests</h4><div class="pg-tag-cloud">@foreach($profile->lifestyle_interests as $tag)<span>{{$interestLabels[$tag]??ucwords(str_replace('_',' ',$tag))}}</span>@endforeach</div>@endif</div>@endif
@if($profile?->partner)<div class="pg-linked-partner"><span>Linked partner</span><a href="{{ route('members.show',$profile->partner) }}"><strong>{{ $profile->partner->display_name ?: $profile->partner->name }}</strong></a></div>@endif
@if($profile?->boundaries&&$privacy->fieldVisible($profile,'boundaries',$tenant->id,$viewer->id,$member->id))<div class="pg-boundaries"><h3>Boundaries & comfort notes</h3><p>{{$profile->boundaries}}</p></div>@endif</div>

<section class="pg-profile-wall"><div class="section-heading"><div><span class="eyebrow">MEMBER WALL</span><h2>{{ $mine?'My Wall':($member->display_name?:$member->name).'’s Wall' }}</h2></div></div>
@if($mine)<form class="panel form-stack pg-community-compose" method="post" action="{{route('community.posts.store')}}" enctype="multipart/form-data">@csrf<textarea name="body" rows="3" maxlength="5000" placeholder="Post to your wall..."></textarea><div class="form-grid"><label>Photo or video<input type="file" name="media" accept="image/*,video/mp4,video/webm,video/quicktime"></label><label>Visibility<select name="visibility"><option value="members">Club members</option><option value="connections">Connections only</option><option value="private">Only me</option></select></label></div><label class="check"><input type="checkbox" name="share_to_club_wall" value="1" checked> Also show this on the main club wall</label><button class="button button-primary">Post</button></form>@endif
@forelse($wallPosts as $post)<article id="post-{{$post->id}}" class="panel pg-community-post"><div class="pg-post-author"><strong>{{$post->user?->display_name?:$post->user?->name}}</strong><small>{{$post->created_at->diffForHumans()}}</small></div>@if($post->body)<p class="pg-post-copy">{{$post->body}}</p>@endif @if($post->media_path)<div class="pg-post-media">@if($post->media_type==='video')<video controls preload="metadata"><source src="{{route('community.posts.media',$post)}}" type="{{$post->media_mime}}"></video>@else<img src="{{route('community.posts.media',$post)}}" alt="Member post image">@endif</div>@endif<div class="pg-post-actions"><form method="post" action="{{route('community.reactions.store',$post)}}">@csrf<select name="reaction"><option value="like">Like</option><option value="love">Love</option><option value="fire">Fire</option><option value="wink">Wink</option><option value="celebrate">Celebrate</option><option value="support">Support</option></select><button class="btn">React</button></form><span class="muted">{{$post->reactions->count()}} reactions · {{$post->comments->count()}} comments</span></div><div class="pg-comments">@foreach($post->comments as $comment)<div class="pg-comment-thread"><div class="pg-comment"><div><a href="{{$comment->user?route('members.show',$comment->user):'#'}}"><strong>{{$comment->user?->display_name?:$comment->user?->name?:'Former member'}}</strong></a><small> · {{$comment->created_at->diffForHumans()}}</small><p>{{$comment->body}}</p><details class="pg-comment-reply"><summary>Reply</summary><form class="form-inline" method="post" action="{{route('community.comments.store',$post)}}">@csrf<input type="hidden" name="parent_id" value="{{$comment->id}}"><input name="body" maxlength="3000" required placeholder="Write a reply"><button class="btn">Reply</button></form></details></div></div>@if($comment->children->isNotEmpty())<div class="pg-comment-children">@foreach($comment->children as $reply)<div class="pg-comment pg-comment-child"><div><strong>{{$reply->user?->display_name?:$reply->user?->name?:'Former member'}}</strong><small> · {{$reply->created_at->diffForHumans()}}</small><p>{{$reply->body}}</p></div></div>@endforeach</div>@endif</div>@endforeach<form class="form-inline pg-comment-compose" method="post" action="{{route('community.comments.store',$post)}}">@csrf<input name="body" maxlength="3000" required placeholder="Write a comment"><button class="btn">Comment</button></form></div></article>@empty<div class="panel"><p class="muted">No wall posts yet.</p></div>@endforelse
{{$wallPosts->links()}}</section>

<section class="pg-profile-gallery"><div class="section-heading"><div><span class="eyebrow">GALLERIES</span><h2>Photos & Videos</h2></div>@if($mine)<a href="{{route('network.index')}}#albums">Manage albums →</a>@endif</div><div class="pg-album-grid">@forelse($albums as $album)<article class="panel pg-album-card"><div class="row-between"><div><h3>{{$album->title}}</h3><small>{{ucfirst($album->visibility)}} · {{$album->photos->count()}} media shown</small></div></div><p>{{$album->description}}</p><div class="pg-album-media-grid">@foreach($album->photos as $media)@if($media->media_type==='video')<video controls preload="metadata"><source src="{{route('network.albums.photos.show',$media)}}" type="{{$media->mime_type}}"></video>@else<img src="{{route('network.albums.photos.show',$media)}}" alt="{{$media->caption}}">@endif @endforeach</div></article>@empty<div class="panel"><p class="muted">No visible albums yet.</p></div>@endforelse</div></section>
</main>
<aside><nav class="panel pg-community-nav"><a href="{{route('community.index')}}">Club Wall</a><a href="{{route('network.index')}}">Member Network</a><a href="{{route('messages.index')}}">Messages</a><a href="{{route('site.events')}}">Events</a><a href="{{route('notifications.index')}}">Notifications</a></nav></aside></div>
</section>
@endsection
