@extends('layouts.app')
@section('title','Members & Galleries · '.$tenant->name)
@section('content')
@php
    $connectionByMember=[];
    foreach($connections as $connection){$otherId=(int)$connection->user_one_id===(int)$viewer->id?(int)$connection->user_two_id:(int)$connection->user_one_id;$connectionByMember[$otherId]=$connection;}
@endphp
<section class="shell section pg-suite-shell">
    <div class="pg-suite-pagehead"><div><span class="eyebrow">MEMBER NETWORK</span><h1>Members, galleries, groups & travel</h1><p>Discover other active members according to their privacy settings, share private photos or videos, build smaller groups and coordinate travel.</p></div><div class="row-actions"><a class="button button-ghost" href="{{ route('community.index') }}">Club Wall</a><a class="button button-primary" href="{{ route('messages.index') }}">Messages</a></div></div>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="notice">{{ $errors->first() }}</div>@endif
    <nav class="pg-network-tabs"><a href="#members">Members</a><a href="#galleries">My Galleries</a><a href="#groups">Groups</a><a href="#travel">Travel</a></nav>

    <section id="members" class="pg-network-section"><div class="pg-network-section-head"><div><span class="eyebrow">MEMBER DIRECTORY</span><h2>Connect with people in your club</h2><p>Members decide whether they appear here and which lifestyle details, location and galleries you may see.</p></div><div class="pg-network-counter"><strong>{{ $connectedIds->count() }}</strong><span>Connections</span></div></div>
        <div class="pg-member-grid">@forelse($directory as $member) @continue(!($member->profile?->discoverable??false)) @php($connection=$connectionByMember[$member->id]??null)
            <article class="panel pg-member-card"><a class="pg-member-card-link" href="{{ route('members.show',$member) }}"><div class="pg-member-avatar">@if($member->profile?->avatar_path)<img src="{{ route('members.media',[$member,'avatar']) }}" alt="">@else{{ strtoupper(substr($member->display_name?:$member->name,0,2)) }}@endif</div><div class="pg-member-copy"><strong>{{ $member->display_name?:$member->name }}</strong>@if($privacy->fieldVisible($member->profile,'location',$tenant->id,$viewer->id,$member->id))<small>{{ $member->profile?->city?:'Location private' }}@if($member->profile?->region), {{ $member->profile->region }}@endif</small>@else<small>Location private</small>@endif @if($privacy->fieldVisible($member->profile,'lifestyle',$tenant->id,$viewer->id,$member->id))<span class="pg-member-type">{{ ucfirst(str_replace('_',' ',$member->profile?->lifestyle_identity??'member')) }}@if($member->profile?->relationship_status) · {{ ucfirst(str_replace('_',' ',$member->profile->relationship_status)) }}@endif</span>@else<span class="pg-member-type">Member</span>@endif @if($member->profile?->headline)<p>{{ $member->profile->headline }}</p>@endif</div></a><div class="pg-member-action">@if(!$connection)<form method="post" action="{{ route('network.connections.request',$member) }}">@csrf<button class="button button-primary">Connect</button></form>@elseif($connection->status==='accepted')<span class="status-pill status-ok">Connected</span><a class="btn" href="{{ route('messages.index',['recipient'=>$member->id]) }}">Message</a>@elseif($connection->status==='pending'&&(int)$connection->requested_by_user_id!==(int)$viewer->id)<form method="post" action="{{ route('network.connections.accept',$connection) }}">@csrf @method('PATCH')<button class="button button-primary">Accept</button></form>@else<span class="status-pill status-pending">Request sent</span>@endif</div></article>
        @empty<div class="panel"><p class="muted">No discoverable active members are available yet.</p></div>@endforelse</div>
    </section>

    <section id="galleries" class="pg-network-section"><div class="pg-network-section-head"><div><span class="eyebrow">PRIVATE GALLERIES</span><h2>Your photos and videos, your audience</h2><p>Create multiple albums and choose club members, connections, explicit grants or only you. Media is served through permission-checked routes instead of public file URLs.</p></div></div>
        <div class="pg-network-two-col"><div class="panel pg-network-form-card"><h3>Create Gallery</h3><form class="form-stack" method="post" action="{{ route('network.albums.create') }}">@csrf<label>Name<input name="title" required maxlength="160" placeholder="Weekend Memories"></label><label>Default access<select name="visibility"><option value="granted">Explicit grants only</option><option value="connections">Connections</option><option value="members">Active club members</option><option value="private">Only me</option></select></label><label>Description<textarea name="description" rows="3" maxlength="3000"></textarea></label><button class="button button-primary">Create Gallery</button></form></div>
        <div class="pg-album-list">@forelse($ownedAlbums as $album) @php($latest=$album->photos()->orderBy('sort_order')->first())<article class="panel pg-album-card"><div class="pg-album-head"><div><span class="eyebrow">{{ strtoupper($album->visibility) }}</span><h3>{{ $album->title }}</h3><small>{{ $album->photos_count }} media item{{ $album->photos_count===1?'':'s' }} · {{ $album->grants_count }} grants</small></div>@if($latest)<a class="pg-album-thumb" href="{{ route('network.albums.photos.show',$latest) }}" target="_blank">@if($latest->media_type==='video')<span class="pg-video-thumb">▶ Video</span>@else<img src="{{ route('network.albums.photos.show',$latest) }}" alt="Gallery preview">@endif</a>@endif</div>@if($album->description)<p class="muted">{{ $album->description }}</p>@endif<details><summary>Add photo or video</summary><form class="form-stack pg-inline-stack" method="post" enctype="multipart/form-data" action="{{ route('network.albums.photos.store',$album) }}">@csrf<label>Media<input name="file" type="file" accept="image/*,video/mp4,video/webm,video/quicktime" required></label><label>Caption<input name="caption" maxlength="255"></label><button class="btn">Upload Privately</button></form></details><details><summary>Grant a member access</summary><form class="form-stack pg-inline-stack" method="post" action="{{ route('network.albums.grants.store',$album) }}">@csrf<label>Member<select name="user_id" required>@foreach($directory as $member)@continue(!($member->profile?->discoverable??false))<option value="{{ $member->id }}">{{ $member->display_name?:$member->name }}</option>@endforeach</select></label><label>Optional expiration<input name="expires_at" type="datetime-local"></label><button class="btn">Grant Access</button></form></details></article>@empty<div class="panel"><p class="muted">Create your first private gallery.</p></div>@endforelse</div></div>
        @if($sharedAlbums->isNotEmpty())<div class="pg-network-subhead"><h3>Shared with you</h3></div><div class="pg-album-shared-grid">@foreach($sharedAlbums as $album) @php($media=$album->photos()->orderBy('sort_order')->first())<article class="panel pg-shared-album"><span class="eyebrow">{{ strtoupper($album->visibility) }}</span><h3>{{ $album->title }}</h3><p class="muted">{{ $album->owner?->display_name?:$album->owner?->name }} · {{ $album->photos_count }} media items</p>@if($media)<a class="button button-ghost" target="_blank" href="{{ route('network.albums.photos.show',$media) }}">Open {{ $media->media_type==='video'?'Video':'Media' }}</a>@endif</article>@endforeach</div>@endif
    </section>

    <section id="groups" class="pg-network-section"><div class="pg-network-section-head"><div><span class="eyebrow">GROUPS</span><h2>Build smaller communities</h2><p>Interest, travel, VIP, new-member, education, social and event groups can have their own wall and invitations.</p></div></div><div class="pg-network-two-col"><div class="panel pg-network-form-card"><h3>Create Group</h3><form class="form-stack" method="post" action="{{ route('network.groups.create') }}">@csrf<label>Name<input name="name" required maxlength="160"></label><label>Group type<select name="group_type"><option value="interest">Interest</option><option value="social">Social</option><option value="travel">Travel</option><option value="event">Event</option><option value="education">Education</option><option value="vip">VIP</option><option value="new_members">New Members</option></select></label><label>Visibility<select name="visibility"><option value="members">Members may join</option><option value="private">Invitation only</option></select></label><label>Description<textarea name="description" rows="3" maxlength="3000"></textarea></label><label class="check"><input type="checkbox" name="allow_member_posts" value="1" checked> Members may post to the group wall</label><button class="button button-primary">Create Group</button></form></div><div class="pg-group-list">@forelse($groups as $group) @php($joined=in_array($group->id,$myGroupIds,true)) @continue($group->visibility==='private'&&!$joined&&(int)$group->owner_user_id!==(int)$viewer->id)<article class="panel pg-group-card"><div><span class="eyebrow">{{ strtoupper(str_replace('_',' ',$group->group_type)) }} · {{ strtoupper($group->visibility) }}</span><h3><a href="{{ route('groups.show',$group) }}">{{ $group->name }}</a></h3><p>{{ $group->description }}</p><small>{{ $group->members_count }} members · by {{ $group->owner?->display_name?:$group->owner?->name }}</small></div><div>@if($joined)<a class="button button-ghost" href="{{ route('groups.show',$group) }}">Open Group</a>@if((int)$group->owner_user_id!==(int)$viewer->id)<form method="post" action="{{ route('network.groups.leave',$group) }}">@csrf @method('DELETE')<button class="btn">Leave</button></form>@endif @elseif($group->visibility==='members')<form method="post" action="{{ route('network.groups.join',$group) }}">@csrf<button class="button button-primary">Join</button></form>@else<span class="status-pill status-pending">Invitation only</span>@endif</div></article>@empty<div class="panel"><p class="muted">No groups yet.</p></div>@endforelse</div></div></section>

    <section id="travel" class="pg-network-section"><div class="pg-network-section-head"><div><span class="eyebrow">TRAVEL</span><h2>See when connections are heading your way</h2><p>Travel plans obey member/connections/private visibility controls.</p></div></div><div class="pg-network-two-col"><div class="panel pg-network-form-card"><h3>Add Travel Plan</h3><form class="form-stack" method="post" action="{{ route('network.travel.create') }}">@csrf<div class="form-grid"><label>City<input name="city" required></label><label>State / region<input name="region"></label><label>Country<input name="country"></label><label>Visibility<select name="visibility"><option value="connections">Connections</option><option value="members">Club members</option><option value="private">Only me</option></select></label><label>Arrive<input type="date" name="starts_on" required></label><label>Depart<input type="date" name="ends_on" required></label></div><label>Notes<textarea name="notes" rows="3" maxlength="3000"></textarea></label><button class="button button-primary">Share Travel Plan</button></form></div><div class="pg-travel-list">@forelse($travelPlans as $plan)<article class="panel pg-travel-card"><div><span class="eyebrow">{{ strtoupper($plan->visibility) }}</span><h3>{{ $plan->city }}@if($plan->region), {{ $plan->region }}@endif</h3><p>{{ $plan->starts_on->format('M j') }}–{{ $plan->ends_on->format('M j, Y') }} · {{ $plan->user?->display_name?:$plan->user?->name }}</p>@if($plan->notes)<p class="muted">{{ $plan->notes }}</p>@endif</div>@if((int)$plan->user_id===(int)$viewer->id)<form method="post" action="{{ route('network.travel.delete',$plan) }}">@csrf @method('DELETE')<button class="btn">Remove</button></form>@endif</article>@empty<div class="panel"><p class="muted">No upcoming member travel plans.</p></div>@endforelse</div></div></section>
</section>
@endsection
