@extends('layouts.app')
@section('title','Live Chat — '.$tenant->name)
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">LIVE COMMUNITY CHAT</span><h1>What’s happening in {{ $tenant->name }}.</h1><p>A real-time members-only room for this community. Use direct Messages when a conversation should move out of the shared room.</p><div class="pg-actions" style="margin-top:20px"><a class="button button-ghost" href="{{ route('community.index') }}">Community wall</a><a class="button button-ghost" href="{{ route('community.groups.index') }}">Groups</a><a class="button button-ghost" href="{{ route('messages.index') }}">Private messages</a></div></div></section>
<section class="pg-page"><div class="pg-shell" style="max-width:1000px"><div class="pg-card"><div id="chat-thread" class="message-thread" style="min-height:430px;max-height:65vh;overflow:auto;padding:4px">
@foreach($messages as $message)<div class="message {{ $message->user_id===auth()->id()?'mine':'' }}" data-chat-id="{{ $message->id }}"><strong>{{ $message->user?->display_name ?: $message->user?->name ?: 'Former member' }}</strong><p>{{ $message->body }}</p><small>{{ $message->created_at->format('M j, g:i A') }}</small></div>@endforeach
</div><form id="chat-form" class="form-inline" method="post" action="{{ route('community.chat.store') }}" style="margin-top:16px;padding-top:16px;border-top:1px solid var(--pg-line)">@csrf<textarea id="chat-body" name="body" maxlength="3000" required placeholder="Message the room" aria-label="Live chat message"></textarea><button class="button button-primary">Send</button></form></div><div class="pg-privacy-note" style="margin-top:14px">Live Chat is a community space, not a public feed. Access requires active membership in {{ $tenant->name }}.</div></div></section>
<script>
(()=>{const thread=document.getElementById('chat-thread'),form=document.getElementById('chat-form'),body=document.getElementById('chat-body'),csrf=document.querySelector('meta[name="csrf-token"]').content;let last=Number(thread.querySelector('[data-chat-id]:last-of-type')?.dataset.chatId||0);const add=m=>{if(thread.querySelector(`[data-chat-id="${m.id}"]`))return;const box=document.createElement('div');box.className='message'+(m.mine?' mine':'');box.dataset.chatId=m.id;const strong=document.createElement('strong');strong.textContent=m.name;const p=document.createElement('p');p.textContent=m.body;const small=document.createElement('small');small.textContent=new Date(m.created_at).toLocaleString();box.append(strong,p,small);thread.appendChild(box);last=Math.max(last,Number(m.id));thread.scrollTop=thread.scrollHeight;};const poll=async()=>{try{const r=await fetch(`{{route('community.chat.poll')}}?after=${last}`,{headers:{Accept:'application/json'}});if(r.ok){const d=await r.json();(d.messages||[]).forEach(add);}}catch(e){}};form.addEventListener('submit',async e=>{e.preventDefault();const text=body.value.trim();if(!text)return;const r=await fetch(form.action,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({body:text})});if(r.ok){const d=await r.json();add(d.message);body.value='';body.focus();}});thread.scrollTop=thread.scrollHeight;setInterval(poll,2000);})();
</script>
@endsection
