@extends('layouts.app')
@section('title',$group->name.' — '.$tenant->name)
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><div class="pg-event-meta"><span class="pg-pill">{{ $group->visibility === 'invite_only' ? 'Invite-only' : 'Member group' }}</span><span class="pg-pill">{{ str_replace('_',' ',ucfirst($group->join_policy)) }}</span></div><h1>{{ $group->name }}</h1><p>{{ $group->description ?: 'A private group inside '.$tenant->name.'.' }}</p><div class="pg-actions" style="margin-top:22px"><a class="button button-ghost" href="{{ route('community.groups.index') }}">All groups</a><a class="button button-ghost" href="{{ route('community.index') }}">Community wall</a>@if(!$membership || $membership->status !== 'active') @if($group->join_policy !== 'invite_only')<form method="post" action="{{ route('community.groups.join',$group) }}">@csrf<button class="button button-primary">{{ $membership?->status === 'pending' ? 'Request pending' : ($group->join_policy === 'open' ? 'Join group' : 'Request to join') }}</button></form>@endif @else<form method="post" action="{{ route('community.groups.leave',$group) }}">@csrf @method('DELETE')<button class="button button-ghost">Leave group</button></form>@endif</div></div></section>
<section class="pg-page"><div class="pg-shell pg-grid" style="grid-template-columns:minmax(0,1.45fr) minmax(280px,.55fr);align-items:start">
<div class="pg-grid">
@if(($membership?->status === 'active' || $canModerate) && ($group->allow_member_posts || $canModerate))
<form class="pg-card form-stack" method="post" action="{{ route('community.groups.posts.store',$group) }}">@csrf<span class="pg-eyebrow">GROUP DISCUSSION</span><h2>Share with {{ $group->name }}</h2><textarea name="body" rows="4" maxlength="5000" required placeholder="Start a private conversation with this group"></textarea><button class="button button-primary">Post to group</button></form>
@endif
@forelse($posts as $post)
<article class="pg-card"><div class="row-between"><div><strong>{{ $post->user?->display_name ?: $post->user?->name ?: 'Former member' }}</strong><small>{{ $post->created_at->diffForHumans() }} @if($post->is_pinned) · Pinned @endif</small></div><div class="pg-actions">@if($canModerate)<form method="post" action="{{ route('community.posts.pin',$post) }}">@csrf @method('PATCH')<button class="button button-ghost">{{ $post->is_pinned ? 'Unpin' : 'Pin' }}</button></form>@endif @if($canModerate || $post->user_id === auth()->id())<form method="post" action="{{ route('community.posts.destroy',$post) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove</button></form>@endif</div></div><p style="white-space:pre-wrap">{{ $post->body }}</p>@php($myReaction=$post->reactions->firstWhere('user_id',auth()->id()))<div class="pg-actions"><form method="post" action="{{ route('community.reactions.store',$post) }}" class="inline-controls">@csrf<select name="reaction"><option value="like">Like</option><option value="love">Love</option><option value="celebrate">Celebrate</option><option value="support">Support</option></select><button class="button button-ghost">React</button></form>@if($myReaction)<form method="post" action="{{ route('community.reactions.destroy',$post) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove {{ $myReaction->reaction }}</button></form>@endif<span class="muted">{{ $post->reactions->count() }} reactions</span></div><div style="margin-top:16px;padding-top:16px;border-top:1px solid var(--pg-line)">@foreach($post->comments as $comment)<div class="list-row"><div><strong>{{ $comment->user?->display_name ?: $comment->user?->name ?: 'Former member' }}</strong><small>{{ $comment->created_at->diffForHumans() }}</small><p>{{ $comment->body }}</p></div>@if($canModerate || $comment->user_id === auth()->id())<form method="post" action="{{ route('community.comments.destroy',$comment) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove</button></form>@endif</div>@endforeach<form class="form-inline" method="post" action="{{ route('community.comments.store',$post) }}">@csrf<input name="body" maxlength="3000" required placeholder="Write a comment"><button class="button button-ghost">Comment</button></form></div></article>
@empty<div class="pg-empty"><h3>No group posts yet</h3><p>This group is ready for its first conversation.</p></div>@endforelse
{{ $posts->links() }}
</div>
<aside class="pg-grid" style="position:sticky;top:140px"><section class="pg-card"><span class="pg-eyebrow">MEMBERS</span><h2>{{ $members->count() }} shown</h2><div class="pg-grid" style="gap:10px">@foreach($members as $member)<div class="row-between"><span>{{ $member->display_name ?: $member->name }}</span><span class="pg-pill">{{ ucfirst($member->pivot->role) }}</span></div>@endforeach</div></section>@if($canModerate && $pending->isNotEmpty())<section class="pg-card"><span class="pg-eyebrow">JOIN REQUESTS</span><h2>Pending</h2>@foreach($pending as $member)<div class="row-between"><span>{{ $member->display_name ?: $member->name }}</span><form method="post" action="{{ route('community.groups.members.approve',[$group,$member->id]) }}">@csrf @method('PATCH')<button class="button button-primary">Approve</button></form></div>@endforeach</section>@endif<div class="pg-privacy-note">Group posts are scoped to active group members. Direct post IDs do not bypass membership access.</div></aside>
</div></section>
@endsection
