@extends('layouts.app')
@section('title','Community — '.$tenant->name)
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">PRIVATE COMMUNITY</span><h1>{{ $tenant->name }} community</h1><p>A members-only wall scoped to this organization. Posts, comments, reactions, groups, messaging and live chat stay inside this tenant.</p><div class="pg-actions" style="margin-top:22px"><a class="button button-ghost" href="{{ route('community.groups.index') }}">Groups</a><a class="button button-ghost" href="{{ route('messages.index') }}">Messages</a><a class="button button-primary" href="{{ route('community.chat') }}">Live chat</a></div></div></section>
<section class="pg-page"><div class="pg-shell pg-grid" style="grid-template-columns:minmax(0,1.45fr) minmax(280px,.55fr);align-items:start">
<div class="pg-grid"><form class="pg-card form-stack" method="post" action="{{ route('community.posts.store') }}">@csrf<span class="pg-eyebrow">COMMUNITY WALL</span><h2>Share with the whole club</h2><textarea name="body" rows="4" maxlength="5000" required placeholder="Share an update with your private community"></textarea><button class="button button-primary">Post to community</button></form>
@forelse($posts as $post)
<article class="pg-card"><div class="row-between"><div><strong>{{ $post->user?->display_name ?: $post->user?->name ?: 'Former member' }}</strong><small>{{ $post->created_at->diffForHumans() }} @if($post->is_pinned) · Pinned @endif</small></div><div class="pg-actions">@if($canModerate)<form method="post" action="{{ route('community.posts.pin',$post) }}">@csrf @method('PATCH')<button class="button button-ghost">{{ $post->is_pinned ? 'Unpin' : 'Pin' }}</button></form>@endif @if($canModerate || $post->user_id === auth()->id())<form method="post" action="{{ route('community.posts.destroy',$post) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove</button></form>@endif</div></div><p style="white-space:pre-wrap">{{ $post->body }}</p>@php($myReaction=$post->reactions->firstWhere('user_id',auth()->id()))<div class="pg-actions"><form method="post" action="{{ route('community.reactions.store',$post) }}" class="inline-controls">@csrf<select name="reaction"><option value="like">Like</option><option value="love">Love</option><option value="celebrate">Celebrate</option><option value="support">Support</option></select><button class="button button-ghost">React</button></form>@if($myReaction)<form method="post" action="{{ route('community.reactions.destroy',$post) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove {{ $myReaction->reaction }}</button></form>@endif<span class="muted">{{ $post->reactions->count() }} reactions</span></div><div style="margin-top:16px;padding-top:16px;border-top:1px solid var(--pg-line)">@foreach($post->comments as $comment)<div class="list-row"><div><strong>{{ $comment->user?->display_name ?: $comment->user?->name ?: 'Former member' }}</strong><small>{{ $comment->created_at->diffForHumans() }}</small><p>{{ $comment->body }}</p></div>@if($canModerate || $comment->user_id === auth()->id())<form method="post" action="{{ route('community.comments.destroy',$comment) }}">@csrf @method('DELETE')<button class="button button-ghost">Remove</button></form>@endif</div>@endforeach<form class="form-inline" method="post" action="{{ route('community.comments.store',$post) }}">@csrf<input name="body" maxlength="3000" required placeholder="Write a comment"><button class="button button-ghost">Comment</button></form></div></article>
@empty<div class="pg-empty"><h3>No community posts yet</h3><p>Start the club-wide conversation, or create a smaller Group for a focused circle.</p></div>@endforelse
{{ $posts->links() }}</div>
<aside class="pg-grid" style="position:sticky;top:140px"><a class="pg-card pg-card-interactive" href="{{ route('community.groups.index') }}"><span class="pg-eyebrow">GROUPS</span><h2>Smaller circles</h2><p class="muted">Join interest-based, invite-only or approval-based spaces without leaving the club’s privacy boundary.</p><span class="text-link">Browse groups →</span></a><a class="pg-card pg-card-interactive" href="{{ route('community.chat') }}"><span class="pg-eyebrow">LIVE CHAT</span><h2>What’s happening now</h2><p class="muted">Real-time conversation for active members of this site.</p><span class="text-link">Open chat →</span></a><div class="pg-privacy-note">Club-wide posts exclude Group-only conversations. Membership checks are enforced on direct post actions too.</div></aside>
</div></section>
@endsection
