<?php

declare(strict_types=1);

function installer_import_product_completion(PDO $pdo): void
{
    $statements = [
        "CREATE TABLE IF NOT EXISTS onboarding_progress (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,member_step TINYINT UNSIGNED NOT NULL DEFAULT 1,member_completed_at TIMESTAMP NULL,tenant_id BIGINT UNSIGNED NULL,tenant_step TINYINT UNSIGNED NOT NULL DEFAULT 1,tenant_completed_at TIMESTAMP NULL,dismissed_prompts JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY onboarding_progress_user_unique(user_id),CONSTRAINT onboarding_progress_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT onboarding_progress_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS favorites (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,target_type VARCHAR(24) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY favorites_user_target_unique(user_id,target_type,target_id),KEY favorites_target_index(target_type,target_id),CONSTRAINT favorites_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS saved_searches (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,search_type VARCHAR(24) NOT NULL DEFAULT 'events',filters JSON NOT NULL,alert_enabled TINYINT(1) NOT NULL DEFAULT 0,last_notified_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),CONSTRAINT saved_searches_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS user_connections (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,requester_id BIGINT UNSIGNED NOT NULL,addressee_id BIGINT UNSIGNED NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'pending',accepted_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY user_connections_pair_unique(requester_id,addressee_id),KEY user_connections_addressee_status_idx(addressee_id,status),CONSTRAINT user_connections_requester_fk FOREIGN KEY(requester_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT user_connections_addressee_fk FOREIGN KEY(addressee_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS user_follows (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,target_type VARCHAR(24) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY user_follows_user_target_unique(user_id,target_type,target_id),KEY user_follows_target_idx(target_type,target_id),CONSTRAINT user_follows_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS user_blocks (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,blocker_id BIGINT UNSIGNED NOT NULL,blocked_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY user_blocks_pair_unique(blocker_id,blocked_id),CONSTRAINT user_blocks_blocker_fk FOREIGN KEY(blocker_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT user_blocks_blocked_fk FOREIGN KEY(blocked_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS user_privacy_settings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,profile_visibility VARCHAR(24) NOT NULL DEFAULT 'members',messages_from VARCHAR(24) NOT NULL DEFAULT 'connections',location_visibility VARCHAR(24) NOT NULL DEFAULT 'city',memberships_visibility VARCHAR(24) NOT NULL DEFAULT 'private',attendance_visibility VARCHAR(24) NOT NULL DEFAULT 'private',online_visibility VARCHAR(24) NOT NULL DEFAULT 'connections',read_receipts TINYINT(1) NOT NULL DEFAULT 1,profile_view_receipts TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY user_privacy_settings_user_unique(user_id),CONSTRAINT user_privacy_settings_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS reviews (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,tenant_id BIGINT UNSIGNED NOT NULL,event_id BIGINT UNSIGNED NULL,rating TINYINT UNSIGNED NOT NULL,body TEXT NULL,status VARCHAR(24) NOT NULL DEFAULT 'published',verified_attendee TINYINT(1) NOT NULL DEFAULT 0,tenant_response TEXT NULL,tenant_responded_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY reviews_tenant_status_idx(tenant_id,status),KEY reviews_event_status_idx(event_id,status),CONSTRAINT reviews_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT reviews_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT reviews_event_fk FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS tenant_member_tags (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(80) NOT NULL,color VARCHAR(16) NOT NULL DEFAULT '#d9bc78',created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY tenant_member_tags_tenant_name_unique(tenant_id,name),CONSTRAINT tenant_member_tags_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS tenant_member_tag_assignments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,tag_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY tenant_member_tag_assignments_tag_user_unique(tag_id,user_id),KEY tenant_member_tag_assignments_tenant_user_idx(tenant_id,user_id),CONSTRAINT tenant_member_tag_assignments_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT tenant_member_tag_assignments_tag_fk FOREIGN KEY(tag_id) REFERENCES tenant_member_tags(id) ON DELETE CASCADE,CONSTRAINT tenant_member_tag_assignments_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS tenant_member_notes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,author_id BIGINT UNSIGNED NULL,body TEXT NOT NULL,is_private TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY tenant_member_notes_tenant_user_idx(tenant_id,user_id),CONSTRAINT tenant_member_notes_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT tenant_member_notes_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT tenant_member_notes_author_fk FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS marketing_contacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,name VARCHAR(255) NULL,email VARCHAR(255) NULL,phone VARCHAR(40) NULL,email_opt_in_at TIMESTAMP NULL,sms_opt_in_at TIMESTAMP NULL,source VARCHAR(48) NOT NULL DEFAULT 'member',status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY marketing_contacts_tenant_status_idx(tenant_id,status),CONSTRAINT marketing_contacts_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT marketing_contacts_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS marketing_campaigns (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,created_by BIGINT UNSIGNED NULL,name VARCHAR(160) NOT NULL,channel VARCHAR(24) NOT NULL DEFAULT 'email',status VARCHAR(24) NOT NULL DEFAULT 'draft',audience JSON NULL,subject VARCHAR(255) NULL,body LONGTEXT NULL,scheduled_at TIMESTAMP NULL,sent_at TIMESTAMP NULL,stats JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),CONSTRAINT marketing_campaigns_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT marketing_campaigns_creator_fk FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS referral_codes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NULL,code VARCHAR(64) NOT NULL,type VARCHAR(24) NOT NULL DEFAULT 'referral',commission_bps SMALLINT UNSIGNED NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY referral_codes_code_unique(code),CONSTRAINT referral_codes_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT referral_codes_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS referral_attributions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,referral_code_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,tenant_id BIGINT UNSIGNED NULL,event_id BIGINT UNSIGNED NULL,order_id BIGINT UNSIGNED NULL,session_key VARCHAR(100) NULL,attributed_at TIMESTAMP NOT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),CONSTRAINT referral_attributions_code_fk FOREIGN KEY(referral_code_id) REFERENCES referral_codes(id) ON DELETE CASCADE,CONSTRAINT referral_attributions_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT referral_attributions_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,CONSTRAINT referral_attributions_event_fk FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE SET NULL,CONSTRAINT referral_attributions_order_fk FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS merchant_accounts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,provider VARCHAR(60) NOT NULL DEFAULT 'manual',provider_account_ref VARCHAR(255) NULL,status VARCHAR(24) NOT NULL DEFAULT 'not_connected',capabilities JSON NULL,onboarded_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY merchant_accounts_tenant_unique(tenant_id),CONSTRAINT merchant_accounts_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS marketplace_ledger_entries (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,order_id BIGINT UNSIGNED NULL,payment_id BIGINT UNSIGNED NULL,type VARCHAR(32) NOT NULL,gross_cents INT UNSIGNED NOT NULL DEFAULT 0,platform_fee_cents INT UNSIGNED NOT NULL DEFAULT 0,tenant_net_cents INT NOT NULL DEFAULT 0,currency VARCHAR(3) NOT NULL DEFAULT 'USD',status VARCHAR(24) NOT NULL DEFAULT 'posted',provider_reference VARCHAR(255) NULL,metadata JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY marketplace_ledger_order_type_unique(order_id,type),KEY marketplace_ledger_tenant_status_idx(tenant_id,status),CONSTRAINT marketplace_ledger_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT marketplace_ledger_order_fk FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE SET NULL,CONSTRAINT marketplace_ledger_payment_fk FOREIGN KEY(payment_id) REFERENCES payments(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS payouts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,amount_cents INT UNSIGNED NOT NULL,currency VARCHAR(3) NOT NULL DEFAULT 'USD',status VARCHAR(24) NOT NULL DEFAULT 'requested',provider_reference VARCHAR(255) NULL,scheduled_at TIMESTAMP NULL,paid_at TIMESTAMP NULL,metadata JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY payouts_tenant_status_idx(tenant_id,status),CONSTRAINT payouts_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS refunds (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,order_id BIGINT UNSIGNED NOT NULL,payment_id BIGINT UNSIGNED NULL,amount_cents INT UNSIGNED NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'requested',provider_reference VARCHAR(255) NULL,reason TEXT NULL,metadata JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),CONSTRAINT refunds_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT refunds_order_fk FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,CONSTRAINT refunds_payment_fk FOREIGN KEY(payment_id) REFERENCES payments(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS membership_subscriptions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,membership_level_id BIGINT UNSIGNED NOT NULL,membership_term_id BIGINT UNSIGNED NULL,provider VARCHAR(60) NOT NULL DEFAULT 'manual',provider_reference VARCHAR(255) NULL,status VARCHAR(24) NOT NULL DEFAULT 'active',billing_interval VARCHAR(24) NOT NULL DEFAULT 'month',amount_cents INT UNSIGNED NOT NULL DEFAULT 0,currency VARCHAR(3) NOT NULL DEFAULT 'USD',current_period_starts_at TIMESTAMP NULL,current_period_ends_at TIMESTAMP NULL,cancel_at_period_end TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY membership_subscriptions_tenant_status_idx(tenant_id,status),CONSTRAINT membership_subscriptions_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT membership_subscriptions_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT membership_subscriptions_level_fk FOREIGN KEY(membership_level_id) REFERENCES tenant_membership_levels(id) ON DELETE CASCADE,CONSTRAINT membership_subscriptions_term_fk FOREIGN KEY(membership_term_id) REFERENCES tenant_membership_terms(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS domain_orders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,domain VARCHAR(253) NOT NULL,provider VARCHAR(60) NOT NULL DEFAULT 'manual',status VARCHAR(32) NOT NULL DEFAULT 'requested',price_cents INT UNSIGNED NULL,currency VARCHAR(3) NOT NULL DEFAULT 'USD',provider_reference VARCHAR(255) NULL,requested_at TIMESTAMP NULL,registered_at TIMESTAMP NULL,renews_at TIMESTAMP NULL,metadata JSON NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY domain_orders_tenant_domain_unique(tenant_id,domain),CONSTRAINT domain_orders_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS push_subscriptions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,endpoint TEXT NOT NULL,endpoint_hash VARCHAR(64) NOT NULL,p256dh TEXT NULL,auth_token TEXT NULL,last_used_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY push_subscriptions_endpoint_hash_unique(endpoint_hash),CONSTRAINT push_subscriptions_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS trust_cases (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,reporter_id BIGINT UNSIGNED NULL,subject_user_id BIGINT UNSIGNED NULL,tenant_id BIGINT UNSIGNED NULL,report_id BIGINT UNSIGNED NULL,type VARCHAR(40) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'open',priority VARCHAR(24) NOT NULL DEFAULT 'normal',assigned_to BIGINT UNSIGNED NULL,notes TEXT NULL,resolution TEXT NULL,resolved_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),KEY trust_cases_status_priority_idx(status,priority),CONSTRAINT trust_cases_reporter_fk FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT trust_cases_subject_fk FOREIGN KEY(subject_user_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT trust_cases_tenant_fk FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,CONSTRAINT trust_cases_report_fk FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE SET NULL,CONSTRAINT trust_cases_assignee_fk FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS cms_section_templates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,scope VARCHAR(24) NOT NULL DEFAULT 'tenant',template_key VARCHAR(80) NOT NULL,label VARCHAR(120) NOT NULL,section_type VARCHAR(60) NOT NULL,content JSON NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,PRIMARY KEY(id),UNIQUE KEY cms_section_templates_key_unique(template_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];
    foreach ($statements as $number => $statement) {
        try { $pdo->exec($statement); } catch (Throwable $e) { throw new RuntimeException('Product completion schema import failed at statement '.($number + 1).': '.$e->getMessage(),0,$e); }
    }

    foreach ([
        ['notification_preferences','email_membership','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','email_tickets','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','push_messages','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','push_events','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','push_membership','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','push_tickets','TINYINT(1) NOT NULL DEFAULT 1'],['notification_preferences','digest_frequency',"VARCHAR(24) NOT NULL DEFAULT 'instant'"],
        ['events','latitude','DECIMAL(10,7) NULL'],['events','longitude','DECIMAL(10,7) NULL'],['events','featured_at','TIMESTAMP NULL'],['events','gallery','JSON NULL'],['events','faq','JSON NULL'],['events','hosts','JSON NULL'],['events','updates','JSON NULL'],
    ] as [$table,$column,$definition]) installer_add_column_if_missing($pdo,$table,$column,$definition);

    $migration='2026_08_23_010000_create_product_completion_suite';
    $stmt=$pdo->prepare('INSERT INTO migrations (migration,batch) SELECT ?,1 WHERE NOT EXISTS (SELECT 1 FROM migrations WHERE migration=?)');
    $stmt->execute([$migration,$migration]);
}
