<?php
namespace App\Http\Controllers;
use App\Contracts\PaymentGateway;use App\Models\Event;use App\Models\Order;use App\Models\OrderItem;use App\Models\Payment;use App\Models\TicketType;use App\Services\TicketIssuer;use App\Tenancy\TenantContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class CheckoutController extends Controller{
 public function store(Request $r,TenantContext $ctx,Event $event,TicketType $ticketType,PaymentGateway $gateway,TicketIssuer $issuer){
  abort_unless($event->status==='published'&&$ticketType->event_id===$event->id&&$ticketType->active,404);if($ctx->check())abort_unless($ctx->id()===$event->tenant_id,404);else abort_unless($event->visibility==='public',404);if(in_array($event->visibility,['private','invite_only'],true))abort_unless($event->rsvps()->where('user_id',$r->user()->id)->where('status','approved')->exists(),403);
  $d=$r->validate(['quantity'=>'required|integer|min:1|max:20']);$qty=(int)$d['quantity'];abort_if($qty>$ticketType->max_per_order,422,'Quantity exceeds the ticket limit.');
  $order=DB::transaction(function()use($event,$ticketType,$qty,$r,$gateway){$type=TicketType::lockForUpdate()->findOrFail($ticketType->id);if($type->sales_start_at&&now()->lt($type->sales_start_at))abort(422,'Ticket sales have not started.');if($type->sales_end_at&&now()->gt($type->sales_end_at))abort(422,'Ticket sales have ended.');if($type->quantity!==null){$sold=(int)OrderItem::where('ticket_type_id',$type->id)->whereHas('order',fn($q)=>$q->whereIn('status',['paid','completed']))->sum('quantity');abort_if($sold+$qty>$type->quantity,422,'Not enough tickets remain.');}$subtotal=$type->price_cents*$qty;$order=Order::create(['public_id'=>(string)Str::uuid(),'tenant_id'=>$event->tenant_id,'event_id'=>$event->id,'user_id'=>$r->user()->id,'status'=>$subtotal===0?'completed':'pending','currency'=>$type->currency,'subtotal_cents'=>$subtotal,'discount_cents'=>0,'fee_cents'=>0,'total_cents'=>$subtotal]);$order->items()->create(['ticket_type_id'=>$type->id,'quantity'=>$qty,'unit_price_cents'=>$type->price_cents,'total_cents'=>$subtotal]);if($subtotal>0){$result=$gateway->begin($order);Payment::create(['order_id'=>$order->id,'provider'=>$gateway->name(),'provider_reference'=>$result['reference']??null,'status'=>$result['status']??'pending','amount_cents'=>$subtotal,'currency'=>$type->currency,'metadata'=>$result]);}return $order;});
  if($order->status==='completed')$issuer->issue($order);return redirect()->route('member.orders.show',$order)->with('status',$order->status==='completed'?'Tickets issued.':'Order created. Payment is pending organizer/payment-provider confirmation.');
 }
}