<?php
namespace App\Http\Controllers;
use App\Models\Event;use App\Models\EventRsvp;use App\Tenancy\TenantContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class RsvpController extends Controller{
 public function store(Request $r,TenantContext $ctx,Event $event){
  abort_unless($event->status==='published',404);if($ctx->check())abort_unless($ctx->id()===$event->tenant_id,404);else abort_unless($event->visibility==='public',404);abort_if(in_array($event->visibility,['private','invite_only'],true),403,'This event requires an organizer invitation.');abort_unless($r->user()->isAdult(),403,'An adult account is required.');if($event->registration_opens_at)abort_if(now()->lt($event->registration_opens_at),422,'Registration has not opened.');if($event->registration_closes_at)abort_if(now()->gt($event->registration_closes_at),422,'Registration is closed.');if($event->requires_verified_profile)abort_unless($r->user()->hasVerifiedEmail()||DB::table('verifications')->where('user_id',$r->user()->id)->where('status','verified')->exists(),403,'A verified profile is required.');
  $d=$r->validate(['guest_count'=>'required|integer|min:1|max:10','answers'=>'nullable|array']);$user=$r->user();if(EventRsvp::where(['event_id'=>$event->id,'user_id'=>$user->id])->whereNotIn('status',['cancelled','rejected'])->exists())return back()->with('status','You already have an RSVP for this event.');
  return DB::transaction(function()use($event,$user,$d){$approved=(int)$event->rsvps()->where('status','approved')->sum('guest_count');$full=$event->capacity!==null&&($approved+$d['guest_count'])>$event->capacity;if($full){if(!$event->waitlist_enabled)abort(422,'This event is full.');DB::table('event_waitlist')->updateOrInsert(['event_id'=>$event->id,'user_id'=>$user->id],['guest_count'=>$d['guest_count'],'position'=>(int)DB::table('event_waitlist')->where('event_id',$event->id)->max('position')+1,'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Event is full; you were added to the waitlist.');}$status=$event->rsvp_mode==='instant'?'approved':'pending';EventRsvp::create(['event_id'=>$event->id,'user_id'=>$user->id,'guest_count'=>$d['guest_count'],'answers'=>$d['answers']??[],'status'=>$status,'approved_at'=>$status==='approved'?now():null]);return back()->with('status',$status==='approved'?'RSVP confirmed.':'RSVP submitted for approval.');});
 }
 public function cancel(Request $r,Event $event){$event->rsvps()->where('user_id',$r->user()->id)->whereNotIn('status',['cancelled'])->update(['status'=>'cancelled']);return back()->with('status','RSVP cancelled.');}
}