<?php

declare(strict_types=1);

$base=dirname(__DIR__);$errors=[];$need=['index.php','private-gather.php','.htaccess','install/index.php','install/lib.php','install/schema.sql','install/community-schema.php','install/product-completion-schema.php','docs/INSTALLATION.md','storage/app','bootstrap/cache'];
foreach($need as $path)if(!file_exists($base.'/'.$path))$errors[]='Missing '.$path;
$rootIndex=(string)@file_get_contents($base.'/index.php');$frontController=(string)@file_get_contents($base.'/private-gather.php');$rootHt=(string)@file_get_contents($base.'/.htaccess');$installIndex=(string)@file_get_contents($base.'/install/index.php');$installLib=(string)@file_get_contents($base.'/install/lib.php');$schema=(string)@file_get_contents($base.'/install/schema.sql');$communitySchema=(string)@file_get_contents($base.'/install/community-schema.php');$productSchema=(string)@file_get_contents($base.'/install/product-completion-schema.php');$userMigration=(string)@file_get_contents($base.'/database/migrations/0001_01_01_000000_create_users_table.php');
$assertions=[
 ['compatibility index delegates to reliable controller',str_contains($rootIndex,"require __DIR__.'/private-gather.php'")],
 ['pre-install flow is inline and redirect-free',str_contains($frontController,"require \$base.'/install/index.php'")&&str_contains($frontController,'X-Private-Gather-Installer: inline')&&!preg_match('/header\s*\(\s*[\'\"]Location:/i',$frontController)],
 ['installed lock recognition',str_contains($frontController,'installed.lock')],['APP_INSTALLED recognition',str_contains($frontController,'APP_INSTALLED')],['subdirectory mount detection',str_contains($frontController,'private_gather_mount_path')&&str_contains($frontController,'DOCUMENT_ROOT')],['canonical installed script name',str_contains($frontController,"'/index.php'")&&str_contains($frontController,"\$_SERVER['SCRIPT_NAME']")],
 ['root application directory protection',str_contains($rootHt,'app|bootstrap|config|database')],['root public asset forwarding',str_contains($rootHt,'public/$1')],['root request reaches reliable controller before directory bypass',str_contains($rootHt,'RewriteRule ^$ private-gather.php')],['explicit index reaches reliable controller',str_contains($rootHt,'RewriteRule ^index\\.php$ private-gather.php')],
 ['installer schema import',str_contains($installIndex,'installer_import_schema')],['installer supplemental community schema import',str_contains($installIndex,'installer_import_private_community')],['installer product completion schema import',str_contains($installIndex,"require __DIR__.'/product-completion-schema.php'")&&str_contains($installIndex,'installer_import_product_completion')],['installer admin creation',str_contains($installIndex,'installer_create_admin')],['installer environment generation',str_contains($installIndex,'installer_write_env')],['installer self removal',str_contains($installIndex,'installer_disable_self')],['installer permanent lock',str_contains($installLib,'installed.lock')],['installer receipt identity present',str_contains($installLib,"'installer_version'")],['installer avoids false DDL transaction',!str_contains($installLib,'$pdo->beginTransaction()')&&str_contains($installLib,"preg_replace('/^\\s*--.*$/m'")],
 ['schema migration registry',str_contains($schema,'CREATE TABLE IF NOT EXISTS migrations')],['browser installer registers invite token data hardening',str_contains($installIndex,'2026_08_18_021500_hash_existing_event_invitation_tokens')],
 ['supplemental installer creates lifestyle membership applications',str_contains($communitySchema,'CREATE TABLE IF NOT EXISTS tenant_membership_applications')],['supplemental installer registers lifestyle membership migration',str_contains($communitySchema,'2026_08_22_230000_create_tenant_membership_applications')],
 ['supplemental installer creates global and tenant badge definitions',str_contains($communitySchema,'CREATE TABLE IF NOT EXISTS badges')&&str_contains($communitySchema,'scope VARCHAR(24)')],['supplemental installer creates badge assignment provenance',str_contains($communitySchema,'CREATE TABLE IF NOT EXISTS user_badges')&&str_contains($communitySchema,'revocation_reason')&&str_contains($communitySchema,'issued_by')],['supplemental installer registers badge system migration',str_contains($communitySchema,'2026_08_22_232000_create_badge_system')],
 ['supplemental installer creates tenant membership levels',str_contains($communitySchema,'CREATE TABLE IF NOT EXISTS tenant_membership_levels')&&str_contains($communitySchema,'profile_eligibility')&&str_contains($communitySchema,'event_discount_percent')],['supplemental installer creates membership renewal terms',str_contains($communitySchema,'CREATE TABLE IF NOT EXISTS tenant_membership_terms')&&str_contains($communitySchema,'cancel_at_period_end')&&str_contains($communitySchema,'current_period_ends_at')],['supplemental installer registers membership level migration',str_contains($communitySchema,'2026_08_22_233000_create_tenant_membership_levels')],
 ['product completion installer creates social/privacy data',str_contains($productSchema,'CREATE TABLE IF NOT EXISTS user_connections')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS user_privacy_settings')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS reviews')],
 ['product completion installer creates CRM and consent-aware growth data',str_contains($productSchema,'CREATE TABLE IF NOT EXISTS tenant_member_tags')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS marketing_contacts')&&str_contains($productSchema,'email_opt_in_at')&&str_contains($productSchema,'sms_opt_in_at')],
 ['product completion installer creates marketplace accounting data',str_contains($productSchema,'CREATE TABLE IF NOT EXISTS marketplace_ledger_entries')&&str_contains($productSchema,'platform_fee_cents')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS payouts')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS refunds')],
 ['product completion installer creates domain/trust data',str_contains($productSchema,'CREATE TABLE IF NOT EXISTS domain_orders')&&str_contains($productSchema,'CREATE TABLE IF NOT EXISTS trust_cases')],
 ['product completion installer registers completion migration',str_contains($productSchema,'2026_08_23_010000_create_product_completion_suite')],
 ['platform admin schema',str_contains($schema,'is_platform_admin')&&str_contains($userMigration,'is_platform_admin')],['fresh 1.0 security schema',str_contains($schema,'two_factor_secret')&&str_contains($schema,'consent_records')],['fresh 1.0 commerce schema',str_contains($schema,'ticket_types')&&str_contains($schema,'orders')&&str_contains($schema,'tickets')],['fresh 1.0 SaaS schema',str_contains($schema,'tenant_subscriptions')&&str_contains($schema,'tenant_branding')],['fresh schema is retry-safe from DDL ALTER traps',!preg_match('/^\s*ALTER\s+TABLE\b/im',$schema)],['plan seed is retry-safe',preg_match('/INSERT\s+INTO\s+plans\b[\s\S]*?ON\s+DUPLICATE\s+KEY\s+UPDATE/i',$schema)===1],['fresh users table includes post-foundation security fields',str_contains($schema,'two_factor_secret')&&str_contains($schema,'privacy_accepted_at')&&str_contains($schema,'adult_confirmed_at')],['fresh event table includes expanded event fields',str_contains($schema,'recurrence_rule')&&str_contains($schema,'waitlist_enabled')&&str_contains($schema,'parent_event_id')],
];
foreach($assertions as[$label,$ok])if(!$ok)$errors[]='Failed assertion: '.$label;
foreach(glob($base.'/database/migrations/*.php')?:[] as $file){$name=basename($file,'.php');if(!str_contains($schema,$name)&&!str_contains($installIndex,$name)&&!str_contains($communitySchema,$name)&&!str_contains($productSchema,$name))$errors[]='Installer does not register migration '.$name;}
if($errors){fwrite(STDERR,"INSTALLER VERIFY: FAIL\n- ".implode("\n- ",$errors)."\n");exit(1);}echo "INSTALLER VERIFY: PASS\n";echo "Inline installer, retry-safe schema, lifestyle memberships, badges, renewal tiers, product-completion schema, migration bookkeeping and protected first-run routing are structurally present.\n";
