@extends('layouts.app')
@section('title',$tenant->name.' — Private Gather')
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pc-club-hero"><div class="pg-shell"><div class="pc-club-cover">@if($tenant->branding?->logo_path)<img src="{{\App\Support\MountUrl::to($tenant->branding->logo_path)}}" alt="{{$tenant->name}} logo">@else<span>{{strtoupper(substr($tenant->name,0,2))}}</span>@endif</div><div><span class="pg-eyebrow">PRIVATE GATHER COMMUNITY PROFILE</span><h1>{{$tenant->name}}</h1><p>{{data_get($tenant->settings,'marketplace_summary')?:'A private lifestyle community using Private Gather for events, membership and connection.'}}</p><div class="pg-trust-row"><span class="pg-pill">{{ucfirst(str_replace('_',' ',$tenant->type))}}</span>@if(data_get($tenant->settings,'city'))<span class="pg-pill">{{data_get($tenant->settings,'city')}}{{data_get($tenant->settings,'region')?', '.data_get($tenant->settings,'region'):''}}</span>@endif @if($rating>0)<span class="pg-pill">★ {{number_format($rating,1)}} verified-community rating</span>@endif</div><div class="pg-actions" style="margin-top:20px">@if($tenant->primaryDomain)<a class="button button-primary" href="https://{{$tenant->primaryDomain->domain}}">Visit club website</a>@endif @auth<form method="post" action="{{$followed?route('follows.destroy',['tenant',$tenant->id]):route('follows.store',['tenant',$tenant->id])}}">@csrf @if($followed)@method('DELETE')@endif<button class="button button-ghost">{{$followed?'Following':'Follow club'}}</button></form><form method="post" action="{{route('favorites.store',['tenant',$tenant->id])}}">@csrf<button class="button button-ghost">Save</button></form>@endauth</div></div></div></section>
<section class="pg-page"><div class="pg-shell pg-grid" style="grid-template-columns:minmax(0,1.4fr) minmax(280px,.6fr);align-items:start"><div class="pg-grid">
<section class="pg-card"><span class="pg-eyebrow">ABOUT</span><h2>A complete community profile</h2><p>{{data_get($tenant->settings,'marketplace_description')?:data_get($tenant->settings,'marketplace_summary')?:'This organization can add its story, standards, amenities and membership details from Club OS.'}}</p>@if($amenities=data_get($tenant->settings,'amenities'))<div class="pc-chip-row">@foreach((array)$amenities as $item)<span>{{$item}}</span>@endforeach</div>@endif</section>
<section><div class="pg-section-head"><div><span class="pg-eyebrow">UPCOMING</span><h2>Events</h2></div></div><div class="pg-grid pg-grid-2">@forelse($events as $event)<a class="pg-card pg-card-interactive" href="{{route('events.show',$event)}}"><span class="pg-pill">{{$event->starts_at->format('M j')}}</span><h3>{{$event->title}}</h3><p class="muted">{{$event->starts_at->format('D · g:i A')}} · {{$event->public_location_label?:$event->city?:'Location protected'}}</p></a>@empty<div class="pg-empty">No public upcoming events.</div>@endforelse</div></section>
<section><div class="pg-section-head"><div><span class="pg-eyebrow">MEMBER FEEDBACK</span><h2>Verified-context reviews</h2><p>Event reviews require a confirmed RSVP or paid ticket. Community reviews require active membership.</p></div></div><div class="pg-grid">@forelse($reviews as $review)<article class="pg-card"><div class="row-between"><strong>{{str_repeat('★',(int)$review->rating)}}{{str_repeat('☆',5-(int)$review->rating)}}</strong>@if($review->verified_attendee)<span class="pg-pill pg-pill-good">Verified attendee</span>@else<span class="pg-pill">Verified member</span>@endif</div><p>{{$review->body}}</p><small>{{$review->display_name?:$review->name}} · {{\Carbon\Carbon::parse($review->created_at)->diffForHumans()}}</small>@if($review->tenant_response)<div class="pc-response"><strong>{{$tenant->name}} responded</strong><p>{{$review->tenant_response}}</p></div>@endif</article>@empty<div class="pg-empty">No published reviews yet.</div>@endforelse</div><div style="margin-top:20px">{{$reviews->links()}}</div></section>
</div><aside class="pg-grid" style="position:sticky;top:120px"><section class="pg-card"><span class="pg-eyebrow">MEMBERSHIP</span><h2>Ways to belong</h2>@forelse($tenant->membershipLevels as $level)<div class="pc-price"><div><strong>{{$level->name}}</strong><small>{{$level->description}}</small></div><span>{{$level->price_cents?'$'.number_format($level->price_cents/100,2):'Contact club'}}</span></div>@empty<p class="muted">Membership details are provided by the club.</p>@endforelse @auth<a class="button button-primary" href="{{route('membership.apply')}}">Apply to Join</a>@else<a class="button button-primary" href="{{route('login')}}">Log in to join</a>@endauth</section><section class="pg-card"><span class="pg-eyebrow">MARKETPLACE VS CLUB SITE</span><p class="muted">This page is the club's Private Gather marketplace profile. Its dedicated tenant website uses its own layout, theme, navigation and branding so visitors can clearly tell the difference.</p></section></aside></div></section>
@endsection
