@extends('layouts.app')
@section('title','Discover — Private Gather')
@push('head')<link rel="stylesheet" href="{{ \App\Support\MountUrl::to('/assets/product-completion.css') }}">@endpush
@section('content')
<section class="pg-page-hero"><div class="pg-shell"><span class="pg-eyebrow">DISCOVER</span><h1>Find your next community, not just another listing.</h1><p>Search upcoming experiences and established lifestyle communities by intent, location and timing. Exact private addresses remain protected.</p>
<form class="pc-filter" method="get"><label>Search<input name="q" value="{{request('q')}}" placeholder="Party, social, club, takeover"></label><label>City<input name="city" value="{{request('city')}}" placeholder="City or metro"></label><label>When<select name="when"><option value="">Any upcoming date</option><option value="today" @selected(request('when')==='today')>Today</option><option value="weekend" @selected(request('when')==='weekend')>This weekend</option><option value="7days" @selected(request('when')==='7days')>Next 7 days</option></select></label><label>Category<select name="category"><option value="">All categories</option>@foreach($categories as $category)<option @selected(request('category')===$category)>{{$category}}</option>@endforeach</select></label><label>Sort<select name="sort"><option value="">Recommended timing</option><option value="popular" @selected(request('sort')==='popular')>Most popular</option><option value="newest" @selected(request('sort')==='newest')>Newest</option></select></label><button class="button button-primary">Update discovery</button></form>
<div class="pc-chip-row"><a href="{{route('discover.index',['when'=>'weekend'])}}">This weekend</a><a href="{{route('discover.index',['sort'=>'popular'])}}">Popular now</a><a href="{{route('site.organizations')}}">All clubs</a>@auth<a href="{{route('saved.index')}}">Saved</a>@endauth</div></div></section>
@if($recommendations->isNotEmpty())<section class="pg-section"><div class="pg-shell"><div class="pg-section-head"><div><span class="pg-eyebrow">FOR YOU</span><h2>{{auth()->check()?'Recommended from your interests':'A good place to start'}}</h2></div></div><div class="pc-rail">@foreach($recommendations as $event)<a class="pc-mini-card" href="{{route('events.show',$event)}}"><span>{{$event->starts_at->format('M j')}}</span><strong>{{$event->title}}</strong><small>{{$event->city?:'Location protected'}} · {{$event->tenant->name}}</small></a>@endforeach</div></div></section>@endif
<section class="pg-page"><div class="pg-shell"><div class="pc-viewbar"><div><span class="pg-eyebrow">UPCOMING</span><h2>{{$events->total()}} events</h2></div><div class="pc-segment"><button type="button" data-view="list" class="is-active">List</button><button type="button" data-view="map">Privacy-safe map</button></div></div>
<div data-discovery-list class="pg-grid pg-grid-3">@forelse($events as $event)<article class="pg-card pg-card-interactive pg-event-card" data-map-point data-lat="{{$event->latitude}}" data-lng="{{$event->longitude}}" data-label="{{$event->title}}"><div class="pg-media">@if($event->cover_image_path)<img src="{{\App\Support\MountUrl::to($event->cover_image_path)}}" alt="">@endif<div class="pg-media-overlay"><span class="pg-pill">{{$event->starts_at->format('M j')}}</span></div></div><div class="pg-event-body"><div class="pg-event-meta">@if($event->category)<span class="pg-pill">{{$event->category}}</span>@endif<span class="pg-pill">{{$event->city?:'Location protected'}}</span></div><h3 class="pg-event-title">{{$event->title}}</h3><p class="pg-event-copy">{{$event->starts_at->format('D, M j · g:i A')}}<br>{{$event->tenant->name}} · {{$event->rsvps_count}} interested/RSVP records</p><div class="pg-actions"><a class="button button-ghost" href="{{route('events.show',$event)}}">View event</a>@auth<form method="post" action="{{route('favorites.store',['event',$event->id])}}">@csrf<button class="button button-ghost">Save</button></form>@endauth</div></div></article>@empty<div class="pg-empty"><h3>No matching events</h3><p>Broaden the filters or save the search and return later.</p></div>@endforelse</div>
<div data-discovery-map class="pc-map" hidden><div class="pc-map-grid"><span>Public event coordinates appear here only when the organizer intentionally provides them.</span></div><div class="pc-map-points"></div></div>
<div style="margin-top:28px">{{$events->links()}}</div>
<section class="pg-section"><div class="pg-section-head"><div><span class="pg-eyebrow">COMMUNITIES</span><h2>Clubs & organizers</h2><p>The marketplace profile introduces the club. Its own tenant website has a visibly different theme and navigation.</p></div></div><div class="pg-grid pg-grid-3">@foreach($clubs as $club)<a class="pg-card pg-card-interactive" href="{{route('clubs.show',$club)}}"><span class="pg-pill">{{ucfirst(str_replace('_',' ',$club->type))}}</span><h3>{{$club->name}}</h3><p class="muted">{{data_get($club->settings,'marketplace_summary')?:'Private lifestyle community'}}</p><small>{{$club->events_count}} upcoming events · {{data_get($club->settings,'city','Location by request')}}</small></a>@endforeach</div></section>
@auth<section class="pg-section"><form method="post" action="{{route('saved-searches.store')}}" class="pg-card form-stack">@csrf<span class="pg-eyebrow">SAVE THIS SEARCH</span><h2>Come back when something changes</h2><input type="hidden" name="search_type" value="events"><input type="hidden" name="filters[q]" value="{{request('q')}}"><input type="hidden" name="filters[city]" value="{{request('city')}}"><input type="hidden" name="filters[when]" value="{{request('when')}}"><input type="hidden" name="filters[category]" value="{{request('category')}}"><label>Name<input name="name" value="{{trim((string)request('city'))?request('city').' events':'My event search'}}" required></label><label class="row-actions"><input type="checkbox" name="alert_enabled" value="1"> Alert me when new matches are available</label><button class="button button-primary">Save search</button></form></section>@endauth
</div></section>
<script>(()=>{const list=document.querySelector('[data-discovery-list]'),map=document.querySelector('[data-discovery-map]'),buttons=document.querySelectorAll('[data-view]');buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const showMap=b.dataset.view==='map';list.hidden=showMap;map.hidden=!showMap;if(showMap){const box=map.querySelector('.pc-map-points');box.innerHTML='';document.querySelectorAll('[data-map-point]').forEach(p=>{const lat=parseFloat(p.dataset.lat),lng=parseFloat(p.dataset.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const dot=document.createElement('span');dot.className='pc-map-dot';dot.style.left=Math.max(2,Math.min(98,((lng+125)/59)*100))+'%';dot.style.top=Math.max(2,Math.min(98,((50-lat)/26)*100))+'%';dot.title=p.dataset.label;dot.setAttribute('aria-label',p.dataset.label);box.appendChild(dot);});}}));})();</script>
@endsection
