@extends('layouts.app')
@section('title',($platformContent['brand_name']??config('app.name')).' — Events, clubs and organizers')
@section('content')
<section class="hero platform-hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">{{$platformContent['hero_eyebrow']}}</span><h1>{{$platformContent['hero_heading']}}</h1><p>{{$platformContent['hero_body']}}</p><div class="hero-actions"><a class="button button-primary button-large" href="{{\App\Support\MountUrl::to($platformContent['hero_primary_url'])}}">{{$platformContent['hero_primary_label']}}</a><a class="button button-ghost button-large" href="{{\App\Support\MountUrl::to($platformContent['hero_secondary_url'])}}">{{$platformContent['hero_secondary_label']}}</a></div></div>
<div class="hero-panel">@if($platformContent['hero_image_url'])<div class="hero-art"><img src="{{\App\Support\MountUrl::to($platformContent['hero_image_url'])}}" alt=""></div>@else<form class="search-card" action="{{route('site.events')}}"><span class="eyebrow">FIND EVENTS</span><label>Search<input name="q" placeholder="Event or keyword"></label><label>City<input name="city" placeholder="City"></label><button class="button button-primary">Search Events</button></form>@endif</div></div></section>
@if(($platformContent['show_featured_events']??'1')==='1')<section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">{{$platformContent['featured_eyebrow']}}</span><h2>{{$platformContent['featured_heading']}}</h2></div><a href="{{route('site.events')}}">View all</a></div><div class="event-grid">@forelse($events as $event)<article class="event-card"><div class="event-image"><span>{{$event->starts_at->format('M d')}}</span></div><div class="event-card-body"><span class="eyebrow">{{strtoupper($event->city?:'LOCATION TBA')}}</span><h3>{{$event->title}}</h3><p>{{$event->starts_at->format('l, F j · g:i A')}}<br>{{$event->tenant->name}}</p><a class="text-link" href="{{route('events.show',$event)}}">View event →</a></div></article>@empty<div class="empty-state"><h3>No public events yet</h3><p>Published public events will appear here automatically.</p></div>@endforelse</div></div></section>@endif
@if(($platformContent['show_organizations']??'1')==='1')<section class="section section-dark"><div class="container"><div class="section-heading"><div><span class="eyebrow">{{$platformContent['organizations_eyebrow']}}</span><h2>{{$platformContent['organizations_heading']}}</h2></div><a href="{{route('site.organizations')}}">Browse all</a></div><div class="card-grid">@foreach($organizations as $org)<article class="card"><span class="pill">{{str_replace('_',' ',ucfirst($org->type))}}</span><h3>{{$org->name}}</h3><p>{{$org->primaryDomain?->domain}}</p>@if($org->primaryDomain)<a class="text-link" href="https://{{$org->primaryDomain->domain}}">Visit website →</a>@endif</article>@endforeach</div></div></section>@endif
@if(($platformContent['show_domain_section']??'1')==='1')<section class="section"><div class="container domain-showcase"><div><span class="eyebrow">{{$platformContent['domain_eyebrow']}}</span><h2>{{$platformContent['domain_heading']}}</h2><p>{{$platformContent['domain_body']}}</p></div><div class="domain-card"><div class="browser-bar"><span></span><span></span><span></span><div class="address">https://yourclub.com/events</div></div><div class="browser-body"><div class="mini-brand">YOUR CLUB</div><div class="mini-heading">Upcoming Events</div><div class="mini-lines"></div></div></div></div></section>@endif
@endsection
